optimizely/javascript-sdk

- lib/plugins/event_dispatcher/index.js
@mikeng13 @aliabbasrizvi @delikat @vraja2
> Incorporate New Optimizely endpoint in event dispatcher

- package.json
> Remove unused json-loader dependency.

- CHANGELOG
> Fix CHANGELOG format

- lib/optimizely/index.js
- lib/optimizely/tests.js
- lib/utils/enums/index.js
OASIS-2268
https://phabricator.optimizely.com/D18996
@optimizely/fullstack-devs @optimizely/oasis-core 
I branched off of elliot/parse-datafile so this PR also includes changes from #74
> Automatically parse datafile when it is JSON

- lib/optimizely/tests.js
OASIS-2268
https://phabricator.optimizely.com/D18997
@optimizely/oasis-core @optimizely/fullstack-devs
> Fix whitespace

- packages/optimizely-sdk/package.json
Opening to run unit + E2E tests
> [PR-87] Bundler-friendly entry point

- packages/optimizely-sdk/package.json
Add [`prepare`](https://docs.npmjs.com/misc/scripts) hook to automatically test and build before publishing.
> chore(publish): add prepare hook

- .travis.yml
> chore: disable srcclr in travis-ci

- packages/optimizely-sdk/README.md
> fix(readme): Don't imply that dist is checked into git

- packages/optimizely-sdk/lib/optimizely/index.tests.js
- packages/optimizely-sdk/package-lock.json
- packages/optimizely-sdk/package.json
Bring some of our dependencies up to date with the latest versions.
> chore: Update dependency versions

- packages/optimizely-sdk/CHANGELOG.MD
- packages/optimizely-sdk/lib/utils/enums/index.js
- packages/optimizely-sdk/package-lock.json
- packages/optimizely-sdk/package.json
- Bumps version
- Prepare to release #187
> chore: Prepare for 2.3.1 release.

- .travis.yml
- Merges in this commit from master to allow PRs opened against this release branch to run unit tests in CI
> chore(ci): Ensure Travis unit tests also run on release branches. (#164)

- packages/optimizely-sdk/CHANGELOG.MD
- Pull in CHANGELOG.md updates from 2.3.0 branch
None
> Add 2.3.0 changelog entry to master

- packages/optimizely-sdk/lib/index.d.ts
- packages/optimizely-sdk/package.json
- Adds Typescript typing for our top-level APIs
Curtesy of @jordangarcia
> feat: Add typescript types.

- .travis.yml
Fix the indentation in .travis.yml.
- OASIS-4076
> fix(srcclr): Properly enable SourceClear

- packages/optimizely-sdk/lib/core/audience_evaluator/index.js
- packages/optimizely-sdk/lib/core/audience_evaluator/index.tests.js
- packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.js
- packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.tests.js
- packages/optimizely-sdk/lib/core/decision_service/index.js
- packages/optimizely-sdk/lib/core/decision_service/index.tests.js
- packages/optimizely-sdk/lib/optimizely/index.tests.js
- packages/optimizely-sdk/lib/utils/attributes_validator/index.js
- packages/optimizely-sdk/lib/utils/attributes_validator/index.tests.js
- packages/optimizely-sdk/lib/utils/enums/index.js
- packages/optimizely-sdk/lib/utils/fns/index.js
This adds logging for audience evaluation.
> feat(Audience Evaluation): Use log messages to explain the outcome of audience evaluation

- .travis.yml
matrix: include: and jobs: include: cannot coexist in .travis.yml so the job in the matrix is converted into a stage and then added to the jobs: include:
> ci(travis): fix skippped test

- packages/optimizely-sdk/CHANGELOG.MD
- packages/optimizely-sdk/lib/index.browser.tests.js
- packages/optimizely-sdk/lib/index.node.tests.js
- packages/optimizely-sdk/lib/utils/enums/index.js
- packages/optimizely-sdk/package-lock.json
- packages/optimizely-sdk/package.json
Prepare for 3.2.0-alpha release
> Prepare for 3.2.0-alpha release

- packages/datafile-manager/CHANGELOG.md
- packages/datafile-manager/package.json
js-sdk-datafile-manager v0.3.0
> js-sdk-datafile-manager v0.3.0

- packages/optimizely-sdk/CHANGELOG.MD
- packages/optimizely-sdk/package-lock.json
- packages/optimizely-sdk/package.json
Update to js-sdk-datafile-manager v0.3.0
Compatibility suite, manual testing
> feat (datafile management): Update js-sdk-datafile-manager dependency to v0.3.0

- packages/optimizely-sdk/CHANGELOG.MD
- packages/optimizely-sdk/lib/index.browser.tests.js
- packages/optimizely-sdk/lib/index.node.tests.js
- packages/optimizely-sdk/lib/utils/enums/index.js
- packages/optimizely-sdk/package-lock.json
- packages/optimizely-sdk/package.json
Prepare for 3.2.0-beta release
> Prepare for 3.2.0-beta release

- packages/optimizely-sdk/CHANGELOG.MD
- packages/optimizely-sdk/lib/index.browser.tests.js
- packages/optimizely-sdk/lib/index.node.tests.js
- packages/optimizely-sdk/lib/utils/enums/index.js
- packages/optimizely-sdk/package-lock.json
- packages/optimizely-sdk/package.json
> Prepare for 3.2.0 release

- packages/datafile-manager/CHANGELOG.md
- packages/datafile-manager/package.json
js-sdk-datafile-manager v0.4.0
> js-sdk-datafile-manager v0.4.0

- packages/optimizely-sdk/CHANGELOG.MD
- packages/optimizely-sdk/lib/index.browser.tests.js
- packages/optimizely-sdk/lib/index.node.tests.js
- packages/optimizely-sdk/lib/utils/enums/index.js
- packages/optimizely-sdk/package-lock.json
- packages/optimizely-sdk/package.json
- Merges the release commit from master into this branch
> chore (optimizely-sdk): prepare for 3.2.1 release (#300)

- packages/optimizely-sdk/README.md
- Link to docs landed on a 404 page
- Manual
- N/A
> fix (docs): Update README with working link to docs

- .travis.yml
- SDK_BRANCH should be passed to FSC.
> fix(ci): branch should be passed to fsc

- packages/optimizely-sdk/CHANGELOG.MD
- packages/optimizely-sdk/lib/index.browser.tests.js
- packages/optimizely-sdk/lib/index.node.tests.js
- packages/optimizely-sdk/lib/utils/enums/index.js
- packages/optimizely-sdk/package-lock.json
- packages/optimizely-sdk/package.json
- Merge the changelog changes back into master
> chore(optimizely-sdk): Prepare for 3.2.2 release. (#350)

- packages/optimizely-sdk/CHANGELOG.MD
- packages/optimizely-sdk/lib/index.browser.tests.js
- packages/optimizely-sdk/lib/index.node.tests.js
- packages/optimizely-sdk/lib/index.react_native.tests.js
- packages/optimizely-sdk/lib/utils/enums/index.js
- packages/optimizely-sdk/package-lock.json
- packages/optimizely-sdk/package.json
> chore: Prepare for optimizely-sdk 3.3.1 release

- .travis.yml
Add Node.js 12 to versions in Travis config file
Existing tests
> chore: Add Node.js 12 to Travis config

- packages/optimizely-sdk/lib/core/optimizely_config/index.js
- packages/optimizely-sdk/lib/optimizely/index.js
Simplified feature variable merging logic in optimizely config.
1. Manually Tested Thoroughly
2. Passed all Unit and Integration tests
None
> refactor(OptimizelyConfig): Simplified feature variable merging logic.

- packages/optimizely-sdk/lib/core/optimizely_config/index.js
- packages/optimizely-sdk/lib/core/project_config/project_config_manager.js
- packages/optimizely-sdk/lib/core/project_config/project_config_manager.tests.js
- packages/optimizely-sdk/lib/optimizely/index.js
Updated the `OptimizelyConfig` implementation to always return cached object. `OptimizelyConfig` object will only be updated when new `ProjectConfig` is received.
Added Unit tests
> feat: Added caching for optimizelyConfig object

- .travis.yml
Add lint rule for spell checking markdown files
> ci(travis): add mdspell

- packages/optimizely-sdk/lib/utils/fns/index.js
- packages/optimizely-sdk/lib/utils/fns/index.tests.js
to reduce package size, we are trying to gradually get rid of lodash library. This PR replaces isNumber function with simple implementation for numbers and strings.
Added unit tests
> Removed dependency on lodash.isNumber

- packages/datafile-manager/.eslintrc.js
- packages/datafile-manager/__test__/backoffController.spec.ts
- packages/datafile-manager/__test__/browserDatafileManager.spec.ts
- packages/datafile-manager/__test__/browserRequest.spec.ts
- packages/datafile-manager/__test__/eventEmitter.spec.ts
- packages/datafile-manager/__test__/httpPollingDatafileManager.spec.ts
- packages/datafile-manager/__test__/nodeDatafileManager.spec.ts
- packages/datafile-manager/__test__/nodeRequest.spec.ts
- packages/datafile-manager/__test__/testUtils.ts
- packages/datafile-manager/src/backoffController.ts
- packages/datafile-manager/src/browserDatafileManager.ts
- packages/datafile-manager/src/browserRequest.ts
- packages/datafile-manager/src/config.ts
- packages/datafile-manager/src/datafileManager.ts
- packages/datafile-manager/src/eventEmitter.ts
- packages/datafile-manager/src/http.ts
- packages/datafile-manager/src/httpPollingDatafileManager.ts
- packages/datafile-manager/src/index.browser.ts
- packages/datafile-manager/src/index.node.ts
- packages/datafile-manager/src/nodeDatafileManager.ts
- packages/datafile-manager/src/nodeRequest.ts
Update years in header comments from files modified recently
Existing tests
> chore(datafile manager): Update years in header comments

- packages/optimizely-sdk/CHANGELOG.MD
- packages/optimizely-sdk/lib/index.browser.tests.js
- packages/optimizely-sdk/lib/index.node.tests.js
- packages/optimizely-sdk/lib/index.react_native.tests.js
- packages/optimizely-sdk/lib/utils/enums/index.js
- packages/optimizely-sdk/package-lock.json
- packages/optimizely-sdk/package.json
Prepare for 4.0.0-rc.1 release
> chore: Prepare for 4.0.0-rc.1 release

- .travis.yml
Update TravisCI configuration Node versions: remove 6, add 14.
Existing tests
> fix(ci): Update Node versions used in tests

- packages/datafile-manager/__test__/nodeDatafileManager.spec.ts
- packages/datafile-manager/src/config.ts
Change domain in default URL template for authenticated datafiles
Updated unit test
> chore(datafile manager): Update auth datafile URL template domain

- packages/datafile-manager/__test__/nodeDatafileManager.spec.ts
- packages/datafile-manager/src/nodeDatafileManager.ts
Fix lint and formatting in datafile manager package
Existing tests
> chore(datafile manager): Fix lint and formatting

- packages/datafile-manager/CHANGELOG.md
- packages/datafile-manager/package-lock.json
- packages/datafile-manager/package.json
Prepare for datafile-manager 0.6.0 release
> chore(datafile manager): Prepare for 0.6.0 release

- packages/utils/CHANGELOG.MD
- packages/utils/package-lock.json
- packages/utils/package.json
Prepare for js-sdk-utils 0.3.0 release
> chore(utils): Prepare for js-sdk-utils 0.3.0 release

- packages/utils/CHANGELOG.MD
- packages/utils/package-lock.json
- packages/utils/package.json
Prepare for js-sdk-utils v0.3.1 release
> chore(utils): Prepare for js-sdk-utils v0.3.1 release

- packages/utils/CHANGELOG.MD
- packages/utils/package-lock.json
- packages/utils/package.json
Prepare for js-sdk-utils v0.3.2 release
> chore(utils): Prepare for js-sdk-utils v0.3.2 release

- packages/optimizely-sdk/CHANGELOG.MD
- packages/optimizely-sdk/lib/index.browser.tests.js
- packages/optimizely-sdk/lib/index.node.tests.js
- packages/optimizely-sdk/lib/index.react_native.tests.js
- packages/optimizely-sdk/lib/utils/enums/index.js
- packages/optimizely-sdk/package-lock.json
- packages/optimizely-sdk/package.json
Prepare for 4.1.0-beta release
> chore: Prepare for 4.1.0-beta release

- packages/event-processor/CHANGELOG.MD
- packages/event-processor/package-lock.json
- packages/event-processor/package.json
> chore: Prepare for event processor 0.5.0 release

- packages/datafile-manager/CHANGELOG.md
- packages/datafile-manager/package-lock.json
- packages/datafile-manager/package.json
> chore(datafile manager): Prepare for 0.7.0 release

- packages/event-processor/package-lock.json
- packages/event-processor/package.json
Updated utils version to `0.4.0`
All Existing tests should pass
> chore(event-processor): Updated utils version

- packages/event-processor/CHANGELOG.MD
- packages/event-processor/package-lock.json
- packages/event-processor/package.json
> chore(event processor): Prepare for 0.6.0 release

- packages/optimizely-sdk/package-lock.json
- packages/optimizely-sdk/package.json
Update versions of `utils`, `event-processor`, `datafile-manager` in `optimizely-sdk`
All existing unit tests and FSC tests should pass.
> chore: Update utils, event-processor and datafile-manager versions

- packages/optimizely-sdk/CHANGELOG.MD
- packages/optimizely-sdk/lib/index.browser.tests.js
- packages/optimizely-sdk/lib/index.node.tests.js
- packages/optimizely-sdk/lib/index.react_native.tests.js
- packages/optimizely-sdk/lib/utils/enums/index.js
- packages/optimizely-sdk/package-lock.json
- packages/optimizely-sdk/package.json
4.2.1 was released from [branch 4.2.x](https://github.com/optimizely/javascript-sdk/tree/4.2.x). This brings changes from the 4.2.1 release commit into master.
Existing tests
> chore: Merge 4.2.1 release into master

- packages/optimizely-sdk/lib/core/decision_service/index.js
- packages/optimizely-sdk/lib/core/event_builder/index.js
- packages/optimizely-sdk/lib/core/notification_center/index.tests.js
- packages/optimizely-sdk/lib/index.browser.js
- packages/optimizely-sdk/lib/index.browser.umdtests.js
- packages/optimizely-sdk/lib/index.node.js
- packages/optimizely-sdk/lib/index.node.tests.js
- packages/optimizely-sdk/lib/index.react_native.js
- packages/optimizely-sdk/lib/optimizely/index.js
- packages/optimizely-sdk/lib/optimizely/index.tests.js
- packages/optimizely-sdk/lib/utils/enums/index.ts
- Convert `enums` module from JS to TS.
> feat: Convert enums module to TS

- packages/optimizely-sdk/lib/core/audience_evaluator/index.js
- packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.js
- packages/optimizely-sdk/lib/core/decision_service/index.js
- packages/optimizely-sdk/lib/core/event_builder/event_helpers.js
- packages/optimizely-sdk/lib/core/event_builder/event_helpers.tests.js
- packages/optimizely-sdk/lib/core/event_builder/index.js
- packages/optimizely-sdk/lib/core/event_builder/index.tests.js
- packages/optimizely-sdk/lib/core/project_config/index.js
- packages/optimizely-sdk/lib/core/project_config/index.tests.js
- packages/optimizely-sdk/lib/core/project_config/project_config_manager.js
- packages/optimizely-sdk/lib/index.browser.js
- packages/optimizely-sdk/lib/index.node.js
- packages/optimizely-sdk/lib/index.react_native.js
- packages/optimizely-sdk/lib/optimizely/index.js
- packages/optimizely-sdk/lib/optimizely/index.tests.js
- packages/optimizely-sdk/lib/utils/attributes_validator/index.ts
- packages/optimizely-sdk/lib/utils/fns/index.tests.js
- packages/optimizely-sdk/lib/utils/fns/index.ts
- Convert `fns` module from JS to TS.
- Existing unit tests + running with local bundle
> feat: Convert fns module to TS

- packages/optimizely-sdk/lib/utils/fns/index.ts
In the process of converting `audience_evaluator` to TS, the following error appeared, which requires revising `assign` function signature to be revised.
- Existing tests
> fix: fix assign function signature

- packages/optimizely-sdk/lib/core/audience_evaluator/index.js
- packages/optimizely-sdk/lib/core/audience_evaluator/index.tests.js
- packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.tests.js
- packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.ts
- packages/optimizely-sdk/lib/shared_types.ts
- Convert `custom_attribute_condition_evaluator` module from JS to TS.
- Existing unit tests and local bundle
> feat: Convert custom_attribute_condition_evaluator to TS

- packages/optimizely-sdk/CHANGELOG.MD
- packages/optimizely-sdk/lib/index.browser.tests.js
- packages/optimizely-sdk/lib/index.node.tests.js
- packages/optimizely-sdk/lib/index.react_native.tests.js
- packages/optimizely-sdk/lib/utils/enums/index.ts
- packages/optimizely-sdk/package-lock.json
- packages/optimizely-sdk/package.json
> chore: Prepare for 4.3.0 release

- packages/optimizely-sdk/CHANGELOG.MD
- packages/optimizely-sdk/lib/index.browser.tests.js
- packages/optimizely-sdk/lib/index.node.tests.js
- packages/optimizely-sdk/lib/index.react_native.tests.js
- packages/optimizely-sdk/lib/utils/enums/index.ts
- packages/optimizely-sdk/package-lock.json
- packages/optimizely-sdk/package.json
> chore: Prepare for 4.3.2 release

- packages/optimizely-sdk/CHANGELOG.MD
- packages/optimizely-sdk/lib/index.browser.tests.js
- packages/optimizely-sdk/lib/index.node.tests.js
- packages/optimizely-sdk/lib/index.react_native.tests.js
- packages/optimizely-sdk/lib/utils/enums/index.ts
- packages/optimizely-sdk/package-lock.json
- packages/optimizely-sdk/package.json
> chore: Prepare for 4.3.3 release

- packages/event-processor/CHANGELOG.MD
- packages/event-processor/package-lock.json
- packages/event-processor/package.json
> chore(event processor): Prepare for 0.7.0 release

- packages/optimizely-sdk/CHANGELOG.MD
- packages/optimizely-sdk/lib/index.browser.tests.js
- packages/optimizely-sdk/lib/index.node.tests.js
- packages/optimizely-sdk/lib/index.react_native.tests.js
- packages/optimizely-sdk/lib/utils/enums/index.ts
- packages/optimizely-sdk/package-lock.json
- packages/optimizely-sdk/package.json
> chore: Prepare for 4.4.0 release

- packages/optimizely-sdk/lib/optimizely/index.ts
- Fix strictNullChecks type errors in optimizely-sdk package.
FSC and unit tests
[SDK-issue 608](https://github.com/optimizely/javascript-sdk/issues/608)
> fix: Fix strictNullChecks type errors 

- packages/optimizely-sdk/CHANGELOG.MD
- packages/optimizely-sdk/lib/index.browser.tests.js
- packages/optimizely-sdk/lib/index.node.tests.js
- packages/optimizely-sdk/lib/index.react_native.tests.js
- packages/optimizely-sdk/lib/utils/enums/index.ts
- packages/optimizely-sdk/package-lock.json
- packages/optimizely-sdk/package.json
> chore: Prepare for 4.4.1 release

- packages/optimizely-sdk/lib/index.d.ts
Newly added Decide APIs have added new interfaces which were not exported, this PR exports them.
1. Manually tested by using decide apis in react sdk.
2. Unit Tests pass
3. Full stack compat suite tests pass.
> update: Export Decide API Interfaces

- packages/optimizely-sdk/lib/optimizely/index.ts
- packages/optimizely-sdk/lib/optimizely_user_context/index.tests.js
- packages/optimizely-sdk/lib/optimizely_user_context/index.ts
- Implemented `trackEvent` from user context
- Manual testing + unit tests
> feat: Implement trackEvent api

- packages/optimizely-sdk/CHANGELOG.MD
- packages/optimizely-sdk/lib/index.browser.tests.js
- packages/optimizely-sdk/lib/index.node.tests.js
- packages/optimizely-sdk/lib/index.react_native.tests.js
- packages/optimizely-sdk/lib/utils/enums/index.ts
- packages/optimizely-sdk/package-lock.json
- packages/optimizely-sdk/package.json
> chore: Prepare for 4.5.1 release

- packages/optimizely-sdk/CHANGELOG.MD
- packages/optimizely-sdk/package-lock.json
- packages/optimizely-sdk/package.json
Bumped Event Processor and Datafile Manager versions to `0.8.1`.
- Manually tested
- All existing tests pass
> update: Bumped Event Processor and Datafile Manager versions to 0.8.1

- packages/optimizely-sdk/lib/plugins/event_dispatcher/index.browser.ts
- Convert event_dispatcher browser plugin to TS
> feat: Convert event_dispatcher browser plugin to TS

- package-lock.json
- package.json
- packages/utils/package-lock.json
- packages/utils/package.json
- Upgrade TS to v4.0.3 in utils package 
- Upgrade TS to v4.0.3 in root directory
> feat: Upgrade TS in root directory and utils package

- packages/optimizely-sdk/lib/plugins/error_handler/index.ts
- Convert error handler plugin to TS
> feat: Convert error handler plugin to TS

- packages/optimizely-sdk/CHANGELOG.MD
- packages/optimizely-sdk/lib/index.browser.tests.js
- packages/optimizely-sdk/lib/index.node.tests.js
- packages/optimizely-sdk/lib/index.react_native.tests.js
- packages/optimizely-sdk/lib/utils/enums/index.ts
- packages/optimizely-sdk/package-lock.json
- packages/optimizely-sdk/package.json
> chore: Prepare for 4.6.1 release

- packages/optimizely-sdk/CHANGELOG.MD
- packages/optimizely-sdk/lib/index.browser.tests.js
- packages/optimizely-sdk/lib/index.node.tests.js
- packages/optimizely-sdk/lib/index.react_native.tests.js
- packages/optimizely-sdk/lib/utils/enums/index.ts
- packages/optimizely-sdk/package-lock.json
- packages/optimizely-sdk/package.json
-  Update Changelog 
-  Update version to 4.6.2
- unit tests + local bundle + FSC
> chore: Prepare for 4.6.2 release

- packages/optimizely-sdk/CHANGELOG.MD
- packages/optimizely-sdk/lib/index.browser.tests.js
- packages/optimizely-sdk/lib/index.node.tests.js
- packages/optimizely-sdk/lib/index.react_native.tests.js
- packages/optimizely-sdk/lib/utils/enums/index.ts
- packages/optimizely-sdk/package-lock.json
- packages/optimizely-sdk/package.json
> chore: Prepare for 4.7.0 release

- packages/optimizely-sdk/CHANGELOG.MD
- packages/optimizely-sdk/lib/index.browser.tests.js
- packages/optimizely-sdk/lib/index.lite.tests.js
- packages/optimizely-sdk/lib/index.node.tests.js
- packages/optimizely-sdk/lib/index.react_native.tests.js
- packages/optimizely-sdk/lib/utils/enums/index.ts
- packages/optimizely-sdk/package-lock.json
- packages/optimizely-sdk/package.json
> chore: prepare for release 4.9.0

- packages/optimizely-sdk/lib/utils/http_request_handler/node_request_handler.ts
- The response promise returned from makeRequest method of NodeRequestHandler was not resolving or rejecting for the ODP graphql api endpoint. This PR fixes the makeRequest method.
[FSSDK-9369](https://jira.sso.episerver.net/browse/FSSDK-9369)
> [FSSDK-9369] fix: fix makeRequest method of NodeRequestHandler class

- packages/optimizely-sdk/lib/core/optimizely_config/index.ts
- This is cherry picked version of the  PR [#828](https://github.com/optimizely/javascript-sdk/pull/828) that needs to be released in 4.9.4
> [FSSDK-9417] refactor: improve OptimizelyConfig instantiation performance

- packages/optimizely-sdk/CHANGELOG.md
- packages/optimizely-sdk/lib/index.browser.tests.js
- packages/optimizely-sdk/lib/index.lite.tests.js
- packages/optimizely-sdk/lib/index.node.tests.js
- packages/optimizely-sdk/lib/utils/enums/index.ts
- packages/optimizely-sdk/package-lock.json
- packages/optimizely-sdk/package.json
- packages/optimizely-sdk/tests/index.react_native.spec.ts
- release 5.0.0-beta2
- FSSDK-9490
> [FSSDK-9490] Prepare for release 5.0.0-beta.2

- packages/optimizely-sdk/package.json
- Ensure optimizely-sdk can be build on windows environment
- https://jira.sso.episerver.net/browse/FSSDK-8740
> [FSSDK-8740] Add script for windows

- packages/optimizely-sdk/lib/core/odp/odp_event_api_manager.ts
- packages/optimizely-sdk/lib/core/odp/odp_event_manager.ts
- packages/optimizely-sdk/lib/index.browser.tests.js
- packages/optimizely-sdk/lib/plugins/odp/event_api_manager/index.browser.ts
- packages/optimizely-sdk/lib/plugins/odp/event_api_manager/index.node.ts
- packages/optimizely-sdk/tests/jsconfig.json
- packages/optimizely-sdk/tests/odpEventApiManager.spec.ts
- packages/optimizely-sdk/tests/odpEventManager.spec.ts
- Refactor OdpEventApiManager to handle odp config update.
- Refactored affected existing tests
- Added new tests for config udpates
- FSSDK-9562
> [FSSDK-9562] refactor odp event api manager to handle odp config

- packages/optimizely-sdk/package-lock.json
- packages/optimizely-sdk/package.json
- remove js-sdk-datafile-manager subpackage from package.json
- FSSDK-8219
> [FSSDK-8219] removed unnecessary subpackage dependency 

- CHANGELOG.md
- lib/index.browser.tests.js
- lib/index.lite.tests.js
- lib/index.node.tests.js
- lib/utils/enums/index.ts
- package-lock.json
- package.json
- tests/index.react_native.spec.ts
- prepare for release 5.0.0-beta3
-
- FSSDK-9562
> [FSSDK-9562] prepare for release 5.0.0-beta3

- CHANGELOG.md
- lib/index.browser.tests.js
- lib/index.lite.tests.js
- lib/index.node.tests.js
- lib/utils/enums/index.ts
- package-lock.json
- package.json
- tests/index.react_native.spec.ts
-  prepare release 5.0.0-beta4
- FSSDK-9611
> [FSSDK-9611] prepare release 5.0.0-beta4

- CHANGELOG.md
- lib/index.browser.tests.js
- lib/index.lite.tests.js
- lib/index.node.tests.js
- lib/utils/enums/index.ts
- package-lock.json
- package.json
- tests/index.react_native.spec.ts
-  prepare for release 5.0.0-beta5
- FSSDK-9585
> [FSSDK-9585] prepare for release 5.0.0-beta5

- lib/index.browser.ts
- lib/modules/event_processor/eventProcessor.ts
- lib/modules/event_processor/eventQueue.ts
- lib/modules/event_processor/v1/v1EventProcessor.react_native.ts
- lib/modules/event_processor/v1/v1EventProcessor.ts
- lib/plugins/event_dispatcher/send_beacon_dispatcher.ts
- lib/plugins/event_processor/index.ts
- lib/shared_types.ts
- package-lock.json
- tests/sendBeaconDispatcher.spec.ts
- tests/v1EventProcessor.spec.ts
-  add support for event dispatcher using sendBeacon which will be used in browser on optimizely client close.
- added new tests for the new dispatcher and event processor
- manually tested that event are being sent using sendBeacon on close
- FSSDK-9605
> [FSSDK-9605] add sendBeacon event dispatcher support

- packages/event-processor/CHANGELOG.md
- packages/event-processor/package-lock.json
- packages/event-processor/package.json
- prepare for release of eventProcessor subpackage v0.10.0
- FSSDK-9605
> [FSSDK-9605] prepare for release of eventProcessor 0.10.0

- packages/optimizely-sdk/CHANGELOG.md
- packages/optimizely-sdk/lib/index.browser.tests.js
- packages/optimizely-sdk/lib/index.lite.tests.js
- packages/optimizely-sdk/lib/index.node.tests.js
- packages/optimizely-sdk/lib/index.react_native.tests.js
- packages/optimizely-sdk/lib/utils/enums/index.ts
- packages/optimizely-sdk/package-lock.json
- packages/optimizely-sdk/package.json
- prepare for release 4.10.0
- FSSDK-9605
> [FSSDK-9605] prepare for release 4.10.0

- CHANGELOG.md
- update CHANGELOG.md for release 4.10.0
- FSSDK-9605
> [FSSDK-9605] update CHANGELOG.md for release 4.10.0

- package-lock.json
- package.json
- update uuid, @types/uuid and ua-parser-js dependencies
- FSSDK-9912
> [FSSDK-9912] update uuid, @types/uuid and ua-parser-js dependencies

- CHANGELOG.md
- LICENSE
- README.md
- lib/index.browser.tests.js
- lib/index.lite.tests.js
- lib/index.node.tests.js
- lib/utils/enums/index.ts
- package-lock.json
- package.json
- tests/index.react_native.spec.ts
- prepare for release 5.0.0
- FSSDK-8580
> [FSSDK-8580] prepare for release 5.0.0

- package-lock.json
- package.json
- bump minimist and karma-mocha version
- existing tests should pass'
- FSSDK-9965
> [FSSDK-9965] bump minimist and karma-mocha

- package-lock.json
- bump follow-redirects
- FSSDK-9966
> [FSSDK-9966] bump follow-redirects

- .github/workflows/javascript.yml
- package.json
- added node 20 to unit test matrix. all tests should pass
- FSSDK-9586
> [FSSDK-9586] update node versions

- CHANGELOG.md
- lib/index.browser.tests.js
- lib/index.lite.tests.js
- lib/index.node.tests.js
- lib/utils/enums/index.ts
- package-lock.json
- package.json
- tests/index.react_native.spec.ts
> [FSSDK-9621] prepare release 5.2.0

- CHANGELOG.md
- lib/index.browser.tests.js
- lib/index.lite.tests.js
- lib/index.node.tests.js
- lib/utils/enums/index.ts
- package-lock.json
- package.json
- tests/index.react_native.spec.ts
- Bump internal semvers
- Update changelog
- No code changes
- FSSDK-9984
> [FSSDK-9984] chore: Prep release

- CHANGELOG.md
- lib/index.browser.tests.js
- lib/index.lite.tests.js
- lib/index.node.tests.js
- lib/utils/enums/index.ts
- package-lock.json
- package.json
- tests/index.react_native.spec.ts
- prepare for release 5.3.1-rc.1
Existing tests should pass
- [FSSDK-10180](https://jira.sso.episerver.net/browse/FSSDK-10180)
> [FSSDK-10180] prepare for release 5.3.1-rc.1

- CHANGELOG.md
- lib/index.browser.tests.js
- lib/index.lite.tests.js
- lib/index.node.tests.js
- lib/utils/enums/index.ts
- package-lock.json
- package.json
- tests/index.react_native.spec.ts
- Prepare for release 5.3.3
[FSSKD-10201](https://jira.sso.episerver.net/browse/FSSDK-10201)
> [FSSDK-10201] prepare for release

- package-lock.json
- package.json
- update decompress-response and ua-parser-js
- FSSDK-9481
> [FSSDK-9481] update dependencies

- .github/workflows/release.yml
> [FSSDK-10464] add release workflow

- lib/core/decision_service/index.tests.js
- lib/index.browser.ts
- lib/index.lite.ts
- lib/index.node.ts
- lib/index.react_native.ts
- lib/notification_center/index.tests.js
- lib/notification_center/index.ts
- lib/optimizely/index.spec.ts
- lib/optimizely/index.tests.js
- lib/optimizely/index.ts
- lib/optimizely_user_context/index.tests.js
- lib/shared_types.ts
- move notification_center to the lib root directory
- FSSDK-10941
> [FSSDK-10941] move notification_center to the lib root directory

- lib/project_config/config_manager_factory.browser.spec.ts
- lib/project_config/config_manager_factory.node.spec.ts
- lib/project_config/config_manager_factory.react_native.spec.ts
- lib/project_config/config_manager_factory.react_native.ts
- lib/project_config/config_manager_factory.spec.ts
- lib/project_config/config_manager_factory.ts
- lib/project_config/datafile_manager.ts
- lib/project_config/optimizely_config.tests.js
- lib/project_config/optimizely_config.ts
- lib/project_config/polling_datafile_manager.spec.ts
- lib/project_config/polling_datafile_manager.ts
- lib/project_config/project_config_manager.ts
- lib/utils/cache/async_storage_cache.react_native.ts
> [FSSDK-10993] additional cleanup for project config manager

- lib/optimizely/index.ts
> [FSSDK-11090] remove unnecessary console.log

- lib/index.browser.tests.js
- lib/optimizely_user_context/index.ts
- #924 has been addressed
- Existing test should pass
- [FSSDK-11098](https://jira.sso.episerver.net/browse/FSSDK-11098)
> [FSSDK-11098] using readyPromise instead of onReady

- lib/entrypoint.test-d.ts
- lib/index.browser.ts
- lib/index.node.ts
- lib/index.react_native.ts
- This will help debug issues where incorrect entrypoint is used by a client
- FSSDK-10992
> [FSSDK-10992] export clientEngine from entrypoint

- lib/core/decision_service/index.spec.ts
- lib/core/decision_service/index.tests.js
- lib/core/decision_service/index.ts
- lib/optimizely/index.tests.js
- lib/optimizely/index.ts
- lib/tests/decision_test_datafile.ts
- vitest.config.mts
> [FSSDK-11236] refactor decision service tests

- lib/entrypoint.test-d.ts
- lib/event_processor/event_processor_factory.browser.ts
- lib/event_processor/event_processor_factory.node.ts
- lib/event_processor/event_processor_factory.react_native.ts
- lib/odp/odp_manager_factory.browser.ts
- lib/odp/odp_manager_factory.node.ts
- lib/odp/odp_manager_factory.react_native.ts
- lib/vuid/vuid_manager_factory.browser.ts
- lib/vuid/vuid_manager_factory.node.ts
- lib/vuid/vuid_manager_factory.react_native.ts
all individual fields of certain factory option objects are optional, so making the whole option object optional by using a defualt empty object
-
> add default empty options for factories

- lib/project_config/project_config.ts
- lib/shared_types.ts
> rename experimentsIds to experimentIds in projectConfig event type

- lib/odp/odp_manager.ts
ODPManager hangs for static config manager. This PR addresses that.
- [FSSDK-11483](https://jira.sso.episerver.net/browse/FSSDK-11483)
> [FSSDK-11483] Bug Bash Fix

- tsconfig.json
> [FSSDK-11503] update build target to ES6

- package.json
> [FSSDK-10843] remove crossbrowser and umd test from prepublish

- .github/workflows/release.yml
> [FSSDK-10843] update release workflow to use node 18

- CHANGELOG.md
- lib/feature_toggle.ts
- lib/index.browser.tests.js
- lib/index.node.tests.js
- lib/index.react_native.spec.ts
- lib/utils/enums/index.ts
- package-lock.json
- package.json
> [FSSDK-11823] prepare release 6.1.0
