CONTRIBUTING.md
@haleybash-optimizely @alda-optimizely @aliabbasrizvi @vraja2 @wangjoshuah @jophde @delikat
=> Update contribution doc to use CLA

package.json
=> Fix package description to reflect new Optimizely X product.

CHANGELOG
=> Fix branch conflicts

.npmignore, Scripts/ci_unit_tests.sh
Write a test script for jenkins ci that mimics travis tests
runs `npm install` and `npm test` for the following node versions
* node 5
* node 0.10
* node
=> Jenkins CI Test Script

CONTRIBUTING.md, README.md
=> Add build and snyk badges.

bower.json
=> Add bower file so we can register with bower registry.

CHANGELOG, index.js, package.json
=> Release version 1.1.1

CHANGELOG, index.js, package.json, tests.js
Bump optimizely-server-sdk to version 1.2.0, which includes:
- Introduce support for event tags.
- Add optional eventTags argument to track method signature.
- Removed optional eventValue argument from track method signature.
- Removed optional sessionId argument from activate and track method signatures.
- Allow log level config on createInstance method.
=> Released 1.3.0

CHANGELOG, index.js, package.json
=> Prepare for 1.3.5 release

package.json
Manually prepending `$(npm bin)` to dependencies is redundant in npm scripts. Npm already prepends `$(npm bin)` to `$PATH` before executing scripts.
=> Remove redundant pathing

lib/core/decision_service/index.tests.js, lib/core/project_config/index.tests.js, lib/optimizely/index.js, lib/optimizely/index.tests.js, lib/tests/test_data.js
This introduces toggleability for a feature flag at the variation level.
=> Add feature toggleability at the variation level.

packages/optimizely-sdk/package.json
* Use the browser entry point instead of a webpack build for `browser` in `package.json` (see [the intended use of the browser package.json field](https://github.com/defunctzombie/package-browser-field-spec) for justification).
* Loosen lodash & uuid version requirements to increase potential for package reuse by bundlers
=> Bundler-friendly entry point

.travis.yml
Travis is erroring ([example](https://travis-ci.org/optimizely/javascript-sdk/jobs/380942404)) when the "node" or "10" target is given, but the tests are passing with node 10 (at least on my machine). Update "node" targets to "9"/"10.0" until this is resolved.
```
$ node --version
v10.0.0
$ npm run test-travis
> @optimizely/optimizely-sdk@2.0.1 test-travis /Users/tbrandt/optly/Projects/javascript-sdk/packages/optimizely-sdk
> npm run test && grunt
...
362 passing (653ms)
```
Mitigation for #102
=> chore(ci): replace node target with v9/v10.0

.travis.yml, packages/optimizely-sdk/lib/optimizely/index.js, packages/optimizely-sdk/lib/plugins/event_dispatcher/index.node.js, packages/optimizely-sdk/lib/plugins/event_dispatcher/index.node.tests.js, packages/optimizely-sdk/package.json, packages/optimizely-sdk/srcclr.yml
Summary:
[`srcclr`](https://optimizely.sourceclear.io/teams/3OOu2k/scans/3772139?login=saml) flags `request` and some of its transitive dependencies as vulnerable. Since we are only barely using it, we can switch to the native node modules `http`/`https` instead. The result is a [clean run](https://optimizely.sourceclear.io/teams/3OOu2k/scans/3772270?login=saml).
```
$ srcclr scan .
SourceClear scanning engine ready
Running the NPM scanner
Scanning completed
Found 12997 lines of code
Processing results...
Processing results complete
Summary Report
Scan ID                                   614c7376-d1ae-4d77-ad5f-3078f6a17917
Scan Date & Time                          May 16 2018 04:26PM PDT
Account type                              PRO
Scan engine                               2.14.7 …
```
=> Fix vulnerabilities by removing request dependency

packages/optimizely-sdk/lib/core/decision_service/index.js, packages/optimizely-sdk/lib/core/decision_service/index.tests.js, packages/optimizely-sdk/lib/core/event_builder/index.js, packages/optimizely-sdk/lib/core/event_builder/index.tests.js, packages/optimizely-sdk/lib/core/project_config/index.js, packages/optimizely-sdk/lib/core/project_config/index.tests.js, packages/optimizely-sdk/lib/index.browser.js, packages/optimizely-sdk/lib/index.browser.tests.js, packages/optimizely-sdk/lib/optimizely/index.tests.js, packages/optimizely-sdk/lib/plugins/event_dispatcher/index.browser.tests.js, packages/optimizely-sdk/lib/plugins/event_dispatcher/index.node.js, packages/optimizely-sdk/lib/plugins/event_dispatcher/index.node.tests.js, packages/optimizely-sdk/lib/plugins/logger/index.tests.js, packages/optimizely-sdk/lib/tests/test_data.js
- Use `npm run lint -- --fix` for most issues, and manually fix the rest
=> chore: fix all lint warnings

packages/optimizely-sdk/package.json
I'm not sure it's conventional to distribute pre-bundled packages.
=> fix(package): Give Node.js consumers the unbundled package

packages/optimizely-sdk/package.json
- Add [`license`](https://docs.npmjs.com/files/package.json#license) key to the manifest
This addresses the warning that is currently being logged during `npm install @optimizely/optimizely-sdk`:
```
npm WARN @optimizely/optimizely-sdk@2.1.1 No license field.
```
and fixes this on our NPM page:
```sh
rm -r node_modules ; npm install
...
```
No warnings!
=> fix(package.json): Add license key

packages/optimizely-sdk/package-lock.json, packages/optimizely-sdk/package.json
- Upgrade mocha 2.5.3 -> 5.2.0
Repro this branch with
```sh
npm install --save-dev mocha@latest
```
Among other things, this addresses the "critical" warning about `growl` visible both here in GitHub and in `npm audit`. The latter is notable because
> npm audit automatically runs when you install a package with npm install
(source: [`npm audit` Getting Started article](https://docs.npmjs.com/getting-started/running-a-security-audit))
For example, expand the `npm install` step of this PR's node 10 build: [link](https://travis-ci.org/optimizely/javascript-sdk/jobs/399773189).
CI
=> chore(deps): Upgrade to mocha@5

.travis.yml
- Re-enable CI against latest Node.js 10.x release
It was disabled in https://github.com/optimizely/javascript-sdk/pull/101, but from the [example failure](https://travis-ci.org/optimizely/javascript-sdk/jobs/380942404) given in that PR, I suspect the bug lies in lerna. No matter now, since lerna has been bypassed since https://github.com/optimizely/javascript-sdk/pull/129.
CI
=> chore(ci): Restore Node.js 10.x to Travis matrix

packages/optimizely-sdk/package.json
- Add [`engines`](https://docs.npmjs.com/files/package.json#engines) property, which will warn users if they `npm install` us and are on a ye olde Node.js version
- Call this package's README the "homepage", rather than the one in the repo root which makes kind of a weird first impression
- Delete extraneous word in package description
Ran `>=4.0.0` through http://jubianchi.github.io/semver-check/ to make sure it allows/denies versions in the way I expect.
=> feat(package.json): Codify supported Node.js in engines property

packages/optimizely-sdk/README.md
Marcelo's asked us to add "Credits" and "Additional Code" sections, where:
> "Credits" is for dependencies that Optimizely distributes (i.e. any code that they download from us, for example, from a repo we set up). If there is a dependency that the customer separately installs / pulls from some non-Optimizely source, then that goes into the "Additional Code" section. The Python SDK, for example, has a few runtime dependencies like `pip` that the customer needs to install when setting up their application environment, but these are not distributed by Optimizely.
I take this to mean Credits is the code checked into this repo (including vendored deps, of which javascript-sdk has none), and "Additional Code" is any other code that is required for prod usage.
=> docs(README): Add credits and additional code

.travis.yml
- Add a `name` to the xbrowser unit test job ([docs](https://docs.travis-ci.com/user/customizing-the-build#Naming-Jobs-within-Matrices))
Found this the other day, I think it's a new feature... [before](https://travis-ci.org/optimizely/javascript-sdk/builds/399797127), [after](https://travis-ci.org/optimizely/javascript-sdk/builds/407273017)
=> feat(ci): Name the xbrowser unit job

packages/optimizely-sdk/lib/core/event_builder/index.js, packages/optimizely-sdk/lib/core/event_builder/index.tests.js, packages/optimizely-sdk/lib/optimizely/index.tests.js
Before it was many snapshots, each with exactly one decision and one conversion event. This is not accurate because decisions for the experiments attached to the same event should be in the same snapshot.
Only conversion events need to have this special logic, because impression events only come from `activate` and `isFeatureEnabled` API (and transitively, `getEnabledFeatures`), which all submit a single impression event for just one experiment.
=> fix(track): Batch decision payloads into the same array in the snapshot.

packages/optimizely-sdk/CHANGELOG.MD, packages/optimizely-sdk/lib/utils/enums/index.js, packages/optimizely-sdk/package.json
- Bumps the version number to prepare for release.
- Bring back the previous changelog entry
=> chore(release): bump to 2.1.3.

packages/optimizely-sdk/lib/optimizely/index.js, packages/optimizely-sdk/lib/optimizely/index.tests.js, packages/optimizely-sdk/lib/utils/enums/index.js
Change the log level from ERROR to DEBUG when we are not able to find the experiment with the given key in the datafile. The reason is because we stopped including non-active experiments in the datafile so if you reference an inexistent experiment, it could mean that the experiment is paused/archived as opposed to existing at all in your project.
=> fix(logs): Change invalid experiment key to debug level.

.travis.yml
Release branches need to have unit tests run on them given that we will soon be in a state (3.x release) where we can't always fast-forward these branches to the latest master.
=> chore(ci): Ensure Travis unit tests also run on release branches.

packages/optimizely-sdk/lib/core/audience_evaluator/index.js, packages/optimizely-sdk/lib/core/audience_evaluator/index.tests.js, packages/optimizely-sdk/lib/core/project_config/index.js, packages/optimizely-sdk/lib/core/project_config/index.tests.js, packages/optimizely-sdk/lib/optimizely/index.tests.js, packages/optimizely-sdk/lib/tests/test_data.js
This updates project config and the audience evaluator to finish the implementation of typed audience evaluation:
- In audience_evaluator, allow evaluation to continue when no user attributes are passed (previously we were immediately returning `false` when no attributes were passed)
- Update project_config: in `createProjectConfig`, set up a by-id object for accessing audiences from both `audiences` and `typedAudiences`. Also, update `getAudiencesForExperiment` to first look in `projectConfig.typedAudiences`, and only look in `projectConfig.audiences` as a fallback.
- Added unit tests checking that all top-level methods that accept user attributes can bucket users into experiments or rollouts that use typed audiences.
- New & existing unit tests
- Ran compatibility suite tests
=> feat (audience match types): Update audience evaluator and project config for new audience match types

packages/optimizely-sdk/lib/core/audience_evaluator/index.js, packages/optimizely-sdk/lib/core/audience_evaluator/index.tests.js, packages/optimizely-sdk/lib/core/condition_evaluator/index.js, packages/optimizely-sdk/lib/core/condition_evaluator/index.tests.js, packages/optimizely-sdk/lib/core/project_config/index.js, packages/optimizely-sdk/lib/core/project_config/index.tests.js, packages/optimizely-sdk/lib/optimizely/index.tests.js, packages/optimizely-sdk/lib/tests/test_data.js, packages/optimizely-sdk/lib/utils/fns/index.js
Introduce support for typed audience evaluation. Includes changes from #171 and #173.
=> feat (audiences): Typed audience evaluation

packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.js, packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.tests.js
Fixes a bug in evaluation of exact match conditions. Before this change, evaluation of a condition with a wrongly-typed `value` property could return a boolean, when it should abort and return `null`. With this change, when `condition.value` of an exact match condition is not a string, boolean, or finite number, the condition will evaluate to `null`.
- Added a test for an exact match condition with a wrongly-typed `value`
- Also added tests for wrongly-typed condition `value`s in 'greater than' and 'less than' conditions
=> fix (typed audience evaluation): When evaluating exact match condition, properly check type of condition value

packages/optimizely-sdk/lib/core/bucketer/index.tests.js, packages/optimizely-sdk/lib/core/decision_service/index.tests.js, packages/optimizely-sdk/lib/core/project_config/index.tests.js, packages/optimizely-sdk/lib/index.browser.tests.js, packages/optimizely-sdk/lib/index.node.tests.js, packages/optimizely-sdk/lib/optimizely/index.tests.js
Inspired by #147, this updates tests to prevent real console output that makes results hard to read.
- In general, we can create loggers with `logToConsole: false` to disable real output. For tests that don’t assert log calls, I used this.
- If a test was previously stubbing only to prevent real output, I removed the stub and used `logToConsole: false` instead.
- Some tests were stubbing both to assert log calls  _and_ to prevent real output. I mostly left these alone.
- As pointed out in #147, real output was sometimes still happening because `log` was called before `sinon.stub`. For these, I added `logToConsole: false`.
- The top-level entry points (index.node.js and index.browser.js) construct loggers internally. To prevent real output in these cases, I stubbed `createLogger`.
Run …
=> fix (tests): Suppress console output in tests

packages/optimizely-sdk/lib/core/project_config/index.js, packages/optimizely-sdk/lib/core/project_config/index.tests.js, packages/optimizely-sdk/lib/tests/test_data.js
Update project config to handle the latest datafile format for 3.0 with typed audience evaluation. `conditions` properties of objects in `typedAudiences` will be `Array`s, and no longer JSON-`Strings`.
Updated typed audiences datafile in test data to the latest format. Existing tests should pass - no change in behavior.
=> fix (audiences): Update project config - no longer expect conditions of audiences in typedAudiences to be strings

packages/optimizely-sdk/lib/core/project_config/index.js, packages/optimizely-sdk/lib/core/project_config/index.tests.js, packages/optimizely-sdk/lib/utils/enums/index.js
- Forced variation key passed as an empty String will be considered as invalid.
- Added unit test for empty string variation key.
=> fix(set-forced-variation): Treats empty variation key as invalid and does not reset variation.

packages/optimizely-sdk/CHANGELOG.MD, packages/optimizely-sdk/README.md, packages/optimizely-sdk/scripts/build_browser_umd.sh
- We need to build and publish the unminified bundle to NPM as we publicly refer to it in our docs.
This is the output of cleaning the local `/dist` directory and building manually with `npm run build-browser-umd`:
```
Hash: 1e3850c525529035af49
Version: webpack 2.7.0
Time: 1222ms
Asset     Size  Chunks             Chunk Names
optimizely.browser.umd.min.js  82.8 kB       0  [emitted]  main
[1] ./lib/utils/enums/index.js 11.8 kB {0} [built]
[3] ./~/sprintf-js/src/sprintf.js 8.67 kB {0} [built]
[4] ./lib/utils/fns/index.js 1.21 kB {0} [built]
[44] ./lib/utils/config_validator/index.js 2.95 kB {0} [built]
[74] ./lib/optimizely/index.js 28.7 kB {0} [built]
[75] ./lib/plugins/error_handler/index.js 809 bytes {0} [built]
[76] ./lib/plugins/event_dispatcher/index.browser.js 2.42 kB {0} [built] …
```
=> fix(bundling): Publish the unminified UMD bundle along with the minified one

packages/optimizely-sdk/lib/index.browser.umdtests.js
- Ported over the last two tests from xbrowser to umd for 'automatically created logger instances' -- these tests are different because they rely on console output, which is inaccessible from the umd bundle optly. Testing that indirectly here by spying on `console.log` and `console.error`
- Ran the tests
- https://optimizely.atlassian.net/browse/OASIS-3799
=> [OASIS-3799] Tests for automatically created logger instances

packages/optimizely-sdk/package.json
- @mjc1283 suggested adding test-ci into the prepublish hook, so I've swapped it out for test-xbrowser there
- OASIS-3799
=> [OASIS-3799]  Adding test-ci to prepublish hoook

packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.tests.js, packages/optimizely-sdk/lib/core/event_builder/index.tests.js, packages/optimizely-sdk/lib/core/project_config/index.tests.js, packages/optimizely-sdk/lib/tests/test_data.js, packages/optimizely-sdk/lib/utils/attributes_validator/index.js, packages/optimizely-sdk/lib/utils/fns/index.js, packages/optimizely-sdk/lib/utils/fns/index.tests.js
Summary
-------
Don't target NAN, INF or -INF doubles
Don't target Values > 2^53. 
Modified fns.isFinite to check if the number is greater than 2^53. 
Test plan
---------
Issues
------
=> feat(attribute_value): Don't target NAN, INF, -INF and > 2^53.

packages/optimizely-sdk/lib/core/decision_service/index.js, packages/optimizely-sdk/lib/core/decision_service/index.tests.js, packages/optimizely-sdk/lib/optimizely/index.tests.js, packages/optimizely-sdk/lib/tests/test_data.js
- Return null variation if experiment key does not exist in feature's experimentIds array.
- "OASIS-3950"
=> fix(decision_service): Return null variation if experiment key does not exist in feature's experimentIds array.

packages/optimizely-sdk/lib/plugins/logger/index.js, packages/optimizely-sdk/lib/plugins/logger/index.tests.js, packages/optimizely-sdk/lib/utils/enums/index.js
* For messages at INFO level, call `console.info` instead of `console.log`.
* Prepend each log message with the message's own log level instead of prepending with the _threshold_ log level. This is particularly important [for contexts like Node.js](https://nodejs.org/api/console.html) where there is (currently) no differentiation between `console.log` and `console.info` or between `console.warn` and `console.error`.
* Fix the code for the "Setting log level" message, which wasn't showing up at all before. Note that this message will only appear when the threshold level is DEBUG.
* Unit tests.
* Manual testing in my local test app.
* OASIS-4021
=> fix(default logger): log each message at the correct level

packages/optimizely-sdk/lib/core/event_builder/index.js, packages/optimizely-sdk/lib/core/event_builder/index.tests.js, packages/optimizely-sdk/lib/optimizely/index.js
- The revenue and event values were excluded from the event object if they evaluated as falsy.
- The fix is to check against `null` instead of performing a truthy check because the utility method will return `null` if the revenue or event values cannot be parsed from the tags.
- Unit tests and integration tests
=> fix(event-tags): do not exclude falsy revenue and event values in the event payload

packages/optimizely-sdk/package-lock.json
SourceClear seems to install `lodash@4.17.10` per our package-lock.json, rather than installing `lodash@4.17.11` (the latest) as they might if installing directly via npm. Update package-lock.json to mitigate this.
Preserve `"lodash": "^4.0.0"` in package.json so that our customers remain free to control their lodash subdependencies.
- OASIS-4112
=> fix(srcclr): Update package-lock.json to satisfy SourceClear

packages/optimizely-sdk/lib/index.browser.umdtests.js
Update UMD script test to reflect the latest expected behavior of the default logger (when the level is INFO, it calls `console.info`)
Run UMD script tests (`npm run test-umdbrowser`)
=> fix (umd script test): Default logger calls console.info when logging at info level

packages/optimizely-sdk/CHANGELOG.MD, packages/optimizely-sdk/lib/utils/enums/index.js, packages/optimizely-sdk/package-lock.json, packages/optimizely-sdk/package.json
Prepare for 3.0.0 release.
- Add items to CHANGELOG.md
- Update version in package.json and enums.NODE_CLIENT_VERSION
=> (chore): Prepare for 3.0.0 release

packages/optimizely-sdk/.prettierrc, packages/optimizely-sdk/lib/index.browser.js, packages/optimizely-sdk/lib/index.browser.tests.js, packages/optimizely-sdk/lib/index.node.js, packages/optimizely-sdk/lib/index.node.tests.js
We should not allow direct requiring of `lib/` files as part of our "public api".  This change exposes `logger` `enums` `errorHandler` and `eventDispatcher` as root level exports.
- Unit tests
- OASIS-4185
=> Add plugins to top level entry points

packages/optimizely-sdk/lib/index.browser.js, packages/optimizely-sdk/lib/index.browser.tests.js, packages/optimizely-sdk/lib/index.node.js, packages/optimizely-sdk/lib/index.node.tests.js
- The `index.browser.js` and `index.node.js` entry points where using an invalid enum `enums.CLIENT_VERSION`.  
This wasn't causing an issue becasue the `Optimizely` constructor defaults to the correct enum.  The fix is to not let this be passed into `Optimizely` and just hard code the value.
- Added unit test to ensure clientVersion after `createInstance`
=> Remove pointer to invalid enums.CLIENT_VERSION

packages/optimizely-sdk/lib/index.browser.js, packages/optimizely-sdk/lib/index.browser.tests.js, packages/optimizely-sdk/lib/index.node.js, packages/optimizely-sdk/lib/index.node.tests.js
- rename `optimizelySdk.logger` to `optimizelySdk.logging`
- unit tests
=> Rename top level optimizelySdk.logger to optimizelySdk.logging

packages/optimizely-sdk/CHANGELOG.MD, packages/optimizely-sdk/lib/index.browser.tests.js, packages/optimizely-sdk/lib/index.node.tests.js, packages/optimizely-sdk/lib/utils/enums/index.js, packages/optimizely-sdk/package.json
- Prepare 3.0.1 release.
See CHANGELOG.md for more info
- unit tests
- OASIS-4189
=> Prepare for 3.0.1 release

packages/optimizely-sdk/package.json
I uncovered this potential issue when trying to install the SDK into the testapp for E2E testing. I recently updated the testapp to use Node 10.6 as base image (up from Node 7) and that is what caused the installation from Github to fail (it doesn't include the `package.json` file inside the `optimizely-sdk` package
=> fix: include package.json in files for those that install from Github.

packages/optimizely-sdk/CHANGELOG.MD, packages/optimizely-sdk/lib/index.browser.tests.js, packages/optimizely-sdk/lib/index.node.tests.js, packages/optimizely-sdk/lib/utils/enums/index.js, packages/optimizely-sdk/package.json
- New APIs for setting `logger` and `logLevel` on the optimizelySDK singleton
- `logger` and `logLevel` are now set globally for all instances of Optimizely.  If you were passing
different loggers to individual instances of Optimizely, logging behavior may now be different.
- Existing unit + compat tests
- OASIS-4297
=> Prepare 3.1.0-beta1 release

packages/optimizely-sdk/CHANGELOG.MD
We want to _further_ clarify the event tracking changes in the 3.0 release. I'm updating the `master` branch but I won't try to update the `v3.0.0` tag.
[Preview link](https://github.com/optimizely/javascript-sdk/blob/nikhil/update-3.0.0-changelog/packages/optimizely-sdk/CHANGELOG.MD)
=> chore(changelog): Update the 3.0.0 changelog

packages/optimizely-sdk/lib/core/decision_service/index.js, packages/optimizely-sdk/lib/core/decision_service/index.tests.js, packages/optimizely-sdk/lib/optimizely/index.js, packages/optimizely-sdk/lib/optimizely/index.tests.js
In preparation for datafile management, change decision service so that the `configObj` is not passed into the constructor. Instead, every method that needs `configObj` accepts it as an argument.
Updated unit tests and compatibility suite.
https://optimizely.atlassian.net/browse/OASIS-4383
=> refactor (datafile management): Remove direct reference to project config object from decision service

packages/optimizely-sdk/lib/core/decision_service/index.js, packages/optimizely-sdk/lib/core/decision_service/index.tests.js, packages/optimizely-sdk/lib/core/project_config/index.js, packages/optimizely-sdk/lib/optimizely/index.js, packages/optimizely-sdk/lib/optimizely/index.tests.js, packages/optimizely-sdk/lib/utils/enums/index.js
- Incorporated new decision notification listener changes.
- Added unit tests.
=> feat(decision-listener): Incorporated new decision notification listener changes.

packages/optimizely-sdk/CHANGELOG.MD, packages/optimizely-sdk/lib/index.browser.tests.js, packages/optimizely-sdk/lib/index.node.tests.js, packages/optimizely-sdk/lib/utils/enums/index.js, packages/optimizely-sdk/package-lock.json, packages/optimizely-sdk/package.json
- Marking activate listener as deprecated in favor of decision listener.
- Updating CHANGELOG for 3.1.0 release.
=> Marking activate listener as deprecated and preparing for 3.1.0 release

packages/optimizely-sdk/CHANGELOG.MD, packages/optimizely-sdk/lib/index.d.ts
Update TypeScript definitions to account for new methods (`onReady`, `close`) and new properties on object accepted by `createInstance` (`datafileOptions`, `sdkKey`)
Manually tested
https://optimizely.atlassian.net/browse/OASIS-4559
=> fix: Update TypeScript definitions for datafile management

packages/optimizely-sdk/CHANGELOG.MD, packages/optimizely-sdk/lib/core/decision_service/index.js, packages/optimizely-sdk/lib/core/decision_service/index.tests.js, packages/optimizely-sdk/lib/core/event_builder/index.js, packages/optimizely-sdk/lib/core/event_builder/index.tests.js, packages/optimizely-sdk/lib/optimizely/index.js, packages/optimizely-sdk/lib/optimizely/index.tests.js, packages/optimizely-sdk/lib/tests/test_data.js
Picked following commits from 3.0 to resolve issues in 2.3.x
- Decision service: Return null variation if experiment key does not exist in feature's experimentIds array.(https://github.com/optimizely/javascript-sdk/pull/206)
- Decision service: Added bucketing id in getVariationForRollout method (https://github.com/optimizely/javascript-sdk/pull/200).
- Event tags: Do not exclude falsy revenue and event values in the event payload. (https://github.com/optimizely/javascript-sdk/pull/213)
=> Picked commits from latest release to resolve issues in 2.3.x

packages/datafile-manager/CHANGELOG.md, packages/datafile-manager/__test__/httpPollingDatafileManager.spec.ts, packages/datafile-manager/src/httpPollingDatafileManager.ts
- When `autoUpdate` is `true`, start the timer for the following request immediately, instead of waiting for the response to start the timer
- When the timeout fires before the response is received, wait for the response to complete and then start the next request immediately. This ensures there is at most 1 request in flight at any time.
Added new unit tests. Manually tested.
https://optimizely.atlassian.net/browse/OASIS-4628
=> fix (datafile management): Update polling behavior

packages/optimizely-sdk/CHANGELOG.MD, packages/optimizely-sdk/lib/optimizely/index.js, packages/optimizely-sdk/lib/optimizely/index.tests.js
`onReady` sets a timeout that fulfills a timeout promise. The timeout promise is only used to race against the ready promise provided by `ProjectConfigManager`. So, as soon as `ProjectConfigManager`'s ready promise is fulfilled, the timeout can be cleared. Before this change, the timeout would only be cleared in the `close` method.
Manual & added unit test
=> fix (datafile management): Clear timeout created in onReady method when it's no longer needed

packages/optimizely-sdk/lib/index.d.ts
- Remove declaring multiple files, this appeared to not be working in the
first place.
- Add logging / errorHandler / eventDispatcher and other top level types
- Fix the `onReady()` signature to include the proper promise resolved
value
- Manually tested with a typescript project importing these types.
- OASIS-4742
=> Update `index.d.ts` file

packages/optimizely-sdk/lib/index.browser.js, packages/optimizely-sdk/lib/index.browser.tests.js, packages/optimizely-sdk/lib/index.node.js, packages/optimizely-sdk/lib/optimizely/index.js, packages/optimizely-sdk/lib/optimizely/index.tests.js, packages/optimizely-sdk/lib/utils/enums/index.js
- Prepare for ReactSDK `0.3.0` release which will happen after javascript-sdk `3.2.0` is released.
- Unit tests
- OASIS-4762
=> Allow react-sdk to be passed in as clientEngine

packages/optimizely-sdk/lib/optimizely/index.js
- This got removed when implementing the event processor.
- "OASIS-4833"
=> Add logging message for optimizely.track()

packages/event-processor/src/eventProcessor.ts, packages/event-processor/src/eventQueue.ts
- Add defaults and a minimum for the event processor's `flushInterval`
- "OASIS-4832"
=> Add minimum for event processor flush interval

packages/event-processor/__tests__/v1EventProcessor.spec.ts, packages/event-processor/src/eventDispatcher.ts, packages/event-processor/src/eventProcessor.ts
- There is a problem right now if you implement your own `eventDispatcher` but dont invoke `callback` with the `response` object, becuase the `eventProcessor` is expecting a `Response` object with `statusCode`.
This change loosens what it expects and also wont throw an error (to be caught by the promise) when invoking `callback()` in a custom event dispatcher
=> try/catch when parsing the eventDispatcher callback response

packages/optimizely-sdk/lib/optimizely/index.js, packages/optimizely-sdk/lib/optimizely/index.tests.js
- Before the event processor used the default values if config value was falsy, thus not respecting `0`
- Added unit tests
=> Use event processor defaults only when config undefined

packages/datafile-manager/CHANGELOG.md, packages/datafile-manager/__test__/httpPollingDatafileManager.spec.ts, packages/datafile-manager/src/httpPollingDatafileManager.ts, packages/datafile-manager/src/index.browser.ts, packages/datafile-manager/src/index.node.ts
The interface `DatafileManager`, defined in [src/datafileManager.ts](https://github.com/optimizely/javascript-sdk/blob/d0ac8821a99dd98a5bd36495d78eb39c4b136f92/packages/datafile-manager/src/datafileManager.ts#L32), is exported from [src/index.node.ts](https://github.com/optimizely/javascript-sdk/blob/d0ac8821a99dd98a5bd36495d78eb39c4b136f92/packages/datafile-manager/src/index.node.ts#L17) and [src/index.browser.ts](https://github.com/optimizely/javascript-sdk/blob/d0ac8821a99dd98a5bd36495d78eb39c4b136f92/packages/datafile-manager/src/index.browser.ts#L17).
However, in each of these top-level entry points, [another export statement](https://github.com/optimizely/javascript-sdk/blob/d0ac8821a99dd98a5bd36495d78eb39c4b136f92/packages/datafile-manager/src/index.browser.ts#L18) appears below, …
=> fix (datafile manager) [OASIS-4715]: Rename top-level exports to avoid conflict with interface name

packages/event-processor/package-lock.json, packages/optimizely-sdk/package-lock.json, packages/optimizely-sdk/package.json
`js-sdk-event-processor@0.2.1` introduces more robustness around implementing custom event dispatchers, by wrapping the callback in `try/catch`.
=> Update optimizely-sdk to event-processor@0.2.1

packages/optimizely-sdk/lib/index.browser.js, packages/optimizely-sdk/lib/index.browser.tests.js
The is an edge case where the `sendPendingEvents()` mechanism keeps sending events because a custom eventDispatcher never invoked the `callback()` denoting the request completed.  This leads to events piling up in localStorage and sending every event each time the SDK is initialized.  
To prevent this only use the pendingEventDispatcher if the default event dispatcher is used, since this guarantees the callback is properly called.
- Added unit tests
- OASIS-4887
=> Dont use pendingEventsDispatcher with user defined eventDispatcher

packages/optimizely-sdk/lib/core/project_config/project_config_manager.js, packages/optimizely-sdk/lib/core/project_config/project_config_manager.tests.js, packages/optimizely-sdk/package-lock.json, packages/optimizely-sdk/package.json
Update js-sdk-datafile-manager dependency to v0.4.0, in which the export `DatafileManager` is renamed to `HttpPollingDatafileManager`.
Updated unit tests. Manually tested.
https://optimizely.atlassian.net/browse/OASIS-4715
=> chore (datafile management): Update js-sdk-datafile-manager dependency to v0.4.0

packages/utils/CHANGELOG.MD, packages/utils/__tests__/utils.spec.ts, packages/utils/src/index.ts
Add `objectEntries` to utils package
Unit tests
=> feat(utils): Add objectEntries to utils package

packages/optimizely-sdk/lib/core/audience_evaluator/index.js, packages/optimizely-sdk/lib/core/audience_evaluator/index.tests.js, packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.js, packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.tests.js, packages/optimizely-sdk/lib/core/decision_service/index.js, packages/optimizely-sdk/lib/core/decision_service/index.tests.js, packages/optimizely-sdk/lib/optimizely/index.js, packages/optimizely-sdk/lib/optimizely/index.tests.js, packages/optimizely-sdk/lib/utils/enums/index.js, packages/optimizely-sdk/package.json
This PR (replacing https://github.com/optimizely/javascript-sdk/pull/216) adds the ability for an SDK consumer to pass their own set of condition evaluators when creating an optimizely instance.
The core motivator for this is to be able to evaluate WEB audience conditions using the Javascript SDK as part of the EDGE project (go/edge).
Future fullstack use cases for this functionality might include audience condition plugins, where the customer would define their own match types and provide their own matchers.
```javascript
/**
* Condition evaluators for conditions that can be evaluated in a Cloudflare worker using
* information like cookies, query parameters, userAgent, etc...
*/
function getConditionEvaluators(inputs) {
return {
cookies: {
evaluate: matchCookies.match.bind(this, { …
```
=> feat(AudienceEvaluator): Add the ability to provide custom condition evaluators

packages/optimizely-sdk/CHANGELOG.MD, packages/optimizely-sdk/package-lock.json, packages/optimizely-sdk/package.json
- Updated lodash dependency in JS SDK to ^4.17.11
Addresses security vulnerabilities in lodash versions < 4.17.11
- Run unit tests with mocha
- Run unit tests with BrowserStack
- Fixes #296
=> Update lodash dependency to ^4.17.11

packages/optimizely-sdk/CHANGELOG.MD, packages/optimizely-sdk/lib/index.browser.tests.js, packages/optimizely-sdk/lib/index.node.tests.js, packages/optimizely-sdk/lib/utils/enums/index.js, packages/optimizely-sdk/package-lock.json, packages/optimizely-sdk/package.json
- Incremented version number
- Updated changelog
-
-
=> chore (optimizely-sdk): prepare for 3.2.1 release

packages/optimizely-sdk/CHANGELOG.MD, packages/optimizely-sdk/lib/optimizely/index.js, packages/optimizely-sdk/lib/optimizely/index.tests.js
The `close` method flushes the event processor's queue. If the queue was non-empty, requests will be sent to the event dispatcher. Users may want to wait until the dispatcher finishes sending these, so we return a `Promise` that fulfills after the event dispatcher calls the "done" callback for each request.
The event processor already returns a `Promise` from its `stop` method, so this change is just making use of that.
New unit tests. Manually tested
https://optimizely.atlassian.net/browse/OASIS-4921
=> feat(event processor)[OASIS-4921] Return Promise from close method representing the close process

package-lock.json, packages/optimizely-sdk/lib/optimizely/index.js, packages/optimizely-sdk/lib/optimizely/index.tests.js, packages/optimizely-sdk/package-lock.json
- Implement `getFeatureVariable` method to return value of variable with any type 
- Create new unit tests to ensure functionality of `getFeatureVariable`
Since Javascript is a dynamically-typed language, it suffices to have a single method return the value of a feature variable rather than have a separate method for each possible feature variable type.
- Create new unit tests to ensure functionality of `getFeatureVariable`
- New unit tests similar to tests for `getFeatureVariable` with specific type
- Create gherkin integration tests using FSC and javascript-testapp
- Fulfills one of the [SDK convenience APIs](https://docs.google.com/document/d/1MCsMioa4TNImryaDdOJJsZwL9j5zFvFIXODArHF3ORs/edit#) (design doc [here](https://docs.google.com/document/d/1CZ0iappDujwgQzYR8oiU9LRVzLho9jGQt2zaB1r …
=> Implement getFeatureVariable and create tests

packages/utils/CHANGELOG.MD, packages/utils/src/index.ts
This PR adds two exports from the utils package:
-  `NOTIFICATION_TYPES`, an `enum`
- `NotificationCenter`, an `interface`.
I want this package to be the home of notification types and the notification center interface, to facilitate using notification center in both the optimizely-sdk package and the event-processor package.
Also, I added a new `LOG_EVENT` notification type. I plan to use this in the event processor when implementing the requirement in OASIS-4976.
Manually tested
https://optimizely.atlassian.net/browse/OASIS-4976
=> feat (utils): Add notification types to utils package

packages/event-processor/__tests__/v1EventProcessor.spec.ts, packages/event-processor/src/eventProcessor.ts
This PR removes transformers, interceptors, and callbacks from the event processor. These extensibility features are currently unused in optimizely-sdk.
Updated unit tests. Deleted tests for removed functionality. Manually tested. All other existing unit tests should pass.
https://optimizely.atlassian.net/browse/OASIS-5151
=> refactor (event processor): Remove transformers, interceptors, and callbacks from event processor

packages/event-processor/__tests__/v1EventProcessor.spec.ts, packages/event-processor/package-lock.json, packages/event-processor/package.json, packages/event-processor/src/eventProcessor.ts, packages/utils/package-lock.json, packages/utils/src/index.ts
With this change, the event processor can be constructed with a notification center. If a notification center is provided, it triggers a log event notification after the event is sent to the event dispatcher.
Added new unit test. Manually tested
https://optimizely.atlassian.net/browse/OASIS-4976
=> feat(event processor): Send log event notification upon event dispatch when notification center available

packages/event-processor/CHANGELOG.MD, packages/event-processor/__tests__/v1EventProcessor.spec.ts, packages/event-processor/src/eventProcessor.ts
Add/change validation for `maxQueueSize` and `flushInterval` inputs to `AbstractEventProcessor`. When invalid, ignore and use default values.
New unit tests
[OASIS-5167](https://optimizely.atlassian.net/browse/OASIS-5167)
=> fix(event processor): If batchSize = 0 or flushInterval = 0, log that values are invalid and use default values instead

packages/event-processor/CHANGELOG.MD, packages/event-processor/__tests__/eventQueue.spec.ts, packages/event-processor/__tests__/v1EventProcessor.spec.ts, packages/event-processor/src/eventProcessor.ts, packages/event-processor/src/eventQueue.ts, packages/event-processor/src/events.ts, packages/event-processor/src/v1/v1EventProcessor.ts
Prior to this change, event processor's buffer could contain events with different contexts. At flush time, the buffered events would be grouped by context and a request would be dispatched for each group.
With this change, we introduce an invariant: all events in the buffer share the same context. As soon as an event with different context is received, the queue is flushed. With this restriction, at most one request is dispatched per flush.
- A new comparator function (`batchComparator`) is provided to `DefaultEventQueue`. When enqueuing an event, `batchComparator` is used to determine whether the incoming event can be included into the current batch. If not, we flush.
- `LogTierV1EventProcessor` provides a `batchComparator` when constructing a `DefaultEventQueue` that checks equality of …
=> fix(event processor): Flush current batch when event with different context received

packages/event-processor/package.json, packages/logging/package.json, packages/utils/package.json
Correct the license field in package.json of these packages. The license is Apache 2.0, not MIT.
=> fix(event processor, logging, utils): Fix license field in package.json

packages/optimizely-sdk/lib/index.browser.js, packages/optimizely-sdk/lib/index.browser.umdtests.js, packages/optimizely-sdk/lib/utils/enums/index.js
With event batching, `optimizely.close()` needs to be called to ensure that events are flushed before the user navigates away.  This PR ensures that optimizely.close() is called when the page unloads by hooking into the `pagehide` event or the `unload` event.
Added a UMD bundle test. Manually tested.
=> feat (event processor/pending events dispatcher): In browser entry point, add event listener for pagehide or unload that calls optimizely.close

packages/optimizely-sdk/lib/index.browser.js, packages/optimizely-sdk/lib/index.browser.tests.js, packages/optimizely-sdk/package-lock.json, packages/optimizely-sdk/package.json
- Updates the lodash dep to ^4.17.11
- Skips pendingEventsDispatcher is there is a user-defined one
=> fix: Merge some bug fixes from master

packages/optimizely-sdk/CHANGELOG.MD, packages/optimizely-sdk/lib/index.browser.tests.js, packages/optimizely-sdk/lib/index.node.tests.js, packages/optimizely-sdk/lib/utils/enums/index.js, packages/optimizely-sdk/package-lock.json, packages/optimizely-sdk/package.json
- Bumps the version to 3.2.2 
- Updates changelog
=> chore(optimizely-sdk): Prepare for 3.2.2 release.

packages/optimizely-sdk/lib/utils/event_processor_config_validator/index.js, packages/optimizely-sdk/lib/utils/event_processor_config_validator/index.tests.js
When `0` is provided for `eventFlushInterval`, it should be ignored and the default used instead.
New unit test
=> fix(event processor): Treat eventFlushInterval 0 as invalid

packages/event-processor/CHANGELOG.MD, packages/event-processor/__tests__/eventQueue.spec.ts, packages/event-processor/__tests__/v1EventProcessor.spec.ts, packages/event-processor/src/eventQueue.ts
Before this change, event processor would continue processing user events after its `stop` method was called. If the batch size limit was reached after `stop` was called, it would dispatch a log event as normal. Worse, the internal queue wasn't being emptied when `stop` was called, which could lead to the same user event being included in two different log events.
With this change, the event processor's internal queue stops accepting events after the event processor is stopped. A warning message is logged, but the event is dropped.
Updated unit tests. Will manually test upon integration of a new version in optimizely-sdk.
=> fix(event processor): Stop accepting events after stop is called

packages/optimizely-sdk/lib/utils/json_schema_validator/index.tests.js
A new patch version of json-schema was released that changed an error message. Our test specifically asserts on the old version of the error message.
With this change we assert on a substring that's included in both the old & new versions.
Run unit tests
=> fix(unit tests): Make test assertion for json schema validation failure less specific

packages/event-processor/CHANGELOG.MD, packages/event-processor/src/pendingEventsStore.ts
React Native does not have localStorage. Added a check to make sure it does not throw error in react native. This is a temporary fix to make sure error is not thrown in React Native. Will implement a better fix in the future.
Manually tested thoroughly.
=> fix(event processor / pending events store): Added a check before accessing localstorage to make it work for React Native

packages/optimizely-sdk/package-lock.json, packages/optimizely-sdk/package.json
Upgrade version of dev dependency `karma-browserstack-launcher` to latest. Fixes issues running cross-browser tests in newer versions of Node.
Run cross-browser tests
=> chore: Update version of karma-browserstack-launcher

packages/optimizely-sdk/lib/core/bucketer/index.js, packages/optimizely-sdk/lib/core/bucketer/index.tests.js, packages/optimizely-sdk/lib/core/decision_service/index.js
**Summary**
When a user is allocated to space in a group that used to be occupied by an experiment, but is now unallocated, the JS SDK logs an error message. This is not an error, so it shouldn't log an error message.
**Expected:**
An info level message saying “User not in any experiment in group” should be logged
**Actual:**
An error level message saying 'Experiment ID " " is not in the datafile' is logged.
=> fix: log error message when user allocated to vacated space in group or experiment

packages/optimizely-sdk/lib/core/project_config/index.js, packages/optimizely-sdk/lib/core/project_config/index.tests.js, packages/optimizely-sdk/lib/tests/test_data.js
In `createProjectConfig`, we [attempt to create an object `experimentFeatureMap`](https://github.com/optimizely/javascript-sdk/blob/9a4d96b170768b3e96f509f6f12854fd37082aad/packages/optimizely-sdk/lib/core/project_config/index.js#L93) whose keys are experiment IDs, and whose values are arrays of feature IDs. We [loop over each experiment ID](https://github.com/optimizely/javascript-sdk/blob/9a4d96b170768b3e96f509f6f12854fd37082aad/packages/optimizely-sdk/lib/core/project_config/index.js#L98) in each feature flag's `experimentIds`, and update `experimentFeatureMap` accordingly.
The problem occurs when one of these experiments is in a group (had a `groupId` property). The inner loop [breaks out by returning `false`](https://github.com/optimizely/javascript-sdk/blob/9a4d96b170768b3e96f509f6f1 …
=> fix: Correct decision notification payload type for getVariation feature test decision

packages/optimizely-sdk/lib/core/optimizely_config/index.js
Fix lint errors and global variable declaration in optimizely_config
Existing tests
=> fix: Lint errors and global variable declaration in optimizely_config

packages/optimizely-sdk/CHANGELOG.MD, packages/optimizely-sdk/lib/index.react_native.js, packages/optimizely-sdk/lib/index.react_native.tests.js
In the [`createInstance` factory method of the React Native entry point](https://github.com/optimizely/javascript-sdk/blob/bbdb2cc892ce412d9e163c078e3007877169d817/packages/optimizely-sdk/lib/index.react_native.js#L58), when no event dispatcher is provided by the caller in the options object, [a value of `undefined` is set on the options object](https://github.com/optimizely/javascript-sdk/blob/bbdb2cc892ce412d9e163c078e3007877169d817/packages/optimizely-sdk/lib/index.react_native.js#L97) that is passed on to the `Optimizely` constructor. This results in an invalid instance that can't dispatch events.
With this fix, the default event dispatcher is used when none is provided by the caller.
Added new unit test
=> fix: Use default event dispatcher in React Native entry point when none provided by user

packages/optimizely-sdk/lib/core/optimizely_config/index.js
`OptimizelyConfig` was using `featureEnabled` directly from projectConfig Object without verifying if experiment is feature experiment or not. Now `featureEnabled` key on `variation` will only be available if experiment is a feature experiment.
=> fix: OptimizelyConfig featureEnabled fix

packages/optimizely-sdk/karma.base.conf.js
Browserstack has stopped supporting emulators and simulators, causing our cross browser tests to fail when we try to launch them on iphone 6. This removes iphone 6 from our test configuration.
Existing tests
=> fix: Remove iphone 6 from browserstack tests

packages/optimizely-sdk/lib/core/decision_service/index.js, packages/optimizely-sdk/lib/core/project_config/index.js, packages/optimizely-sdk/lib/core/project_config/index.tests.js, packages/optimizely-sdk/lib/optimizely/index.tests.js, packages/optimizely-sdk/lib/utils/enums/index.js
- removed launch status check within isActive
- removed or altered associated unit tests
- altered a log message
The only thing I didn't touch was the test data's testExperimentLaunched test since it was being used to check functionality unrelated to the launched status.
=> Deprecate launched status check

packages/optimizely-sdk/CHANGELOG.MD, packages/optimizely-sdk/lib/index.browser.tests.js, packages/optimizely-sdk/lib/index.node.tests.js, packages/optimizely-sdk/lib/index.react_native.tests.js, packages/optimizely-sdk/lib/utils/enums/index.js, packages/optimizely-sdk/package-lock.json, packages/optimizely-sdk/package.json
=> chore: prepare for release 3.4.0

packages/optimizely-sdk/lib/index.d.ts
Added Optimizely Config in Typescript
Don't have any specific testplan but react sdk should work for OptimizelyConfig
=> Added Optimizely Config in Typescript

packages/optimizely-sdk/CHANGELOG.MD, packages/optimizely-sdk/lib/index.browser.tests.js, packages/optimizely-sdk/lib/index.node.tests.js, packages/optimizely-sdk/lib/index.react_native.tests.js, packages/optimizely-sdk/lib/utils/enums/index.js, packages/optimizely-sdk/package-lock.json, packages/optimizely-sdk/package.json
=> chore: prepare for release 3.4.1

packages/optimizely-sdk/lib/core/audience_evaluator/index.tests.js
#288 introduced an exploratory new feature, the ability to pass custom condition evaluators to the SDK constructor via the option `UNSTABLE_conditionEvaluators`.
The AudienceEvaluator (and its tests) were refactored as a part of that PR, but no tests were added to assert that the `UNSTABLE_conditionEvaluators` worked when passed.
This PR introduces tests to ensure that functionality continues to work.
Unit tests added to assert that:
- You cannot override the built in `custom_attribute` evaluator
- A passed in custom condition evaluator will evaluate conditions of that type
- That the audience condition, user attributes, and logger instance are all passed to the custom evaluator
- CJS-3815
=> chore (Regression Test)[CJS-3815]: Add tests for passing in a custom condition evaluator

packages/event-processor/CHANGELOG.MD, packages/event-processor/__tests__/requestTracker.spec.ts, packages/event-processor/__tests__/v1EventProcessor.spec.ts, packages/event-processor/package-lock.json, packages/event-processor/src/eventProcessor.ts, packages/event-processor/src/requestTracker.ts
Add tracking functionality to `EventProcessor` for every request sent by its dispatcher. This is implemented in a `RequestTracker` class.
`RequestTracker` exposes a method (`onRequestsComplete`) to get a `Promise` that fulfills after the completion of requests in-flight at the time of the call.
`stop` is updated to return the promise from `RequestTracker` `onRequestsComplete`.
- New and existing unit tests
- Manually tested in browser, Node, & Lambda environments
https://optimizely.atlassian.net/browse/OASIS-5907
=> fix (event processor) [OASIS-5907]: stop promise tracks in-flight dispatcher requests

packages/optimizely-sdk/CHANGELOG.MD, packages/optimizely-sdk/lib/optimizely/index.js, packages/optimizely-sdk/package-lock.json, packages/optimizely-sdk/package.json
Update to js-sdk-event-processor v0.4.0, which supports tracking in-flight event dispatcher requests in its `stop()` promise. The `close` promise (of `Optimizely`) is based on the event processor's `stop` promise, so by this upgrade, we get the new functionality. I updated the `close` doc comment to talk about this new behavior.
Existing tests
Manually tested in Node, browser, and Lambda environments
https://optimizely.atlassian.net/browse/OASIS-5907
=> feat (Optimizely) [OASIS-5907]: close promise tracks in-flight event dispatcher requests

packages/optimizely-sdk/lib/index.d.ts
Fix the type definitions for `OptimizelyConfig`. The value types in the various maps had an incorrect extra wrapper object.
Manually tested in a local TS app
=> fix: Fix OptimizelyConfig TypeScript definitions

packages/optimizely-sdk/lib/utils/fns/index.js
Removed `lodash.filter` because it wasnt being used anywhere in the project. This is part of an effort to remove lodash dependency to reduce bundle size.
All Unit tests and Full Stack SDK compatibility passed
=> Removed lodash.filter

packages/optimizely-sdk/lib/plugins/event_dispatcher/index.browser.js, packages/optimizely-sdk/lib/utils/fns/index.js, packages/optimizely-sdk/lib/utils/fns/index.tests.js
To reduce package size, we are trying to gradually get rid of lodash library. This PR removes the `map` function.
All tests pass after this change.
=> Removed dependency on lodash.map

packages/optimizely-sdk/lib/index.d.ts
- optimizely.close() does return a Promise. See [here](https://github.com/optimizely/javascript-sdk/blob/9fe10a04a1b30e255e8f5e9f5af433ce5a5565be/packages/optimizely-sdk/lib/optimizely/index.js#L977)
- [Docs](https://docs.developers.optimizely.com/full-stack/docs/event-batching-javascript-node#section-close-optimizely-on-application-exit) also mentions awaiting on close
Fixes `'await' has no effect on the type of this expression.ts(80007)`
=> Fix return type for close

packages/optimizely-sdk/lib/utils/fns/index.js, packages/optimizely-sdk/lib/utils/json_schema_validator/index.js
to reduce package size, we are trying to gradually get rid of lodash library. This PR replaces `isArray` function with `Array.isArray`. Because lodash is also using this standard built-in objects from javascript. 
All tests pass after this change.
=> Removed dependency on lodash.isArray

packages/optimizely-sdk/lib/core/decision_service/index.js, packages/optimizely-sdk/lib/core/project_config/index.js, packages/optimizely-sdk/lib/optimizely/index.js, packages/optimizely-sdk/lib/utils/fns/index.js, packages/optimizely-sdk/lib/utils/fns/index.tests.js
to reduce package size, we are trying to gradually get rid of lodash library. This PR replaces isEmpty function simple implementation for object. Because we are using this methods for object only
Added unit tests for this
=> Removed dependency on lodash.isEmpty

packages/optimizely-sdk/lib/utils/fns/index.js, packages/optimizely-sdk/lib/utils/fns/index.tests.js
Replaced lodash values function with `keyBy` from js-sdk-utils and added missing functionality. This is part of an effort to remove lodash dependency to reduce bundle size.
1) Added Unit tests
2) All Unit tests and Full Stack SDK compatibility passed
=> Removed dependency on lodash.keyBy

packages/optimizely-sdk/lib/core/audience_evaluator/index.js, packages/optimizely-sdk/lib/core/decision_service/index.js, packages/optimizely-sdk/lib/core/project_config/index.js, packages/optimizely-sdk/lib/index.browser.js, packages/optimizely-sdk/lib/index.react_native.js, packages/optimizely-sdk/lib/utils/fns/index.js
to reduce package size, we are trying to gradually get rid of lodash library. This PR replaces `assign` function with `Object.assign`. Also added a polyfill method to support old browsers. Polyfill was taken from MDN. 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill
All tests pass after this change.
=> Removed dependency on lodash.assign

packages/optimizely-sdk/lib/core/notification_center/index.js, packages/optimizely-sdk/lib/core/project_config/index.js, packages/optimizely-sdk/lib/utils/fns/index.js
to reduce package size, we are trying to gradually get rid of lodash library. This PR removes the implementation of fns.forEach and replaced it with default forEach method of arrays and Object.Keys for maps
All tests are passing
=> Removed dependency on lodash.forEach

packages/optimizely-sdk/lib/core/event_builder/event_helpers.js, packages/optimizely-sdk/lib/core/event_builder/index.js, packages/optimizely-sdk/lib/core/notification_center/index.js, packages/optimizely-sdk/lib/core/project_config/index.js, packages/optimizely-sdk/lib/optimizely/index.js, packages/optimizely-sdk/lib/utils/attributes_validator/index.tests.js, packages/optimizely-sdk/lib/utils/fns/index.js, packages/optimizely-sdk/lib/utils/fns/index.tests.js
Removed `lodash.forOwn` function and replaced all the usaes with `Object.keys`. This is part of an effort to remove lodash dependency to reduce bundle size.
All Unit tests and Full Stack SDK compatibility passed
=> refactor: Removed dependency on lodash.forOwn

packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.js, packages/optimizely-sdk/lib/optimizely/index.js, packages/optimizely-sdk/lib/utils/attributes_validator/index.js, packages/optimizely-sdk/lib/utils/event_processor_config_validator/index.js, packages/optimizely-sdk/lib/utils/fns/index.js, packages/optimizely-sdk/lib/utils/fns/index.tests.js
to reduce package size, we are trying to gradually get rid of lodash library. This PR replaces isFinite function with simple implementation numbers. As we are using this methods for numbers or strings only
Update Unit Tests
=> Removed dependency on lodash.isFinite

packages/optimizely-sdk/lib/optimizely/index.js, packages/optimizely-sdk/lib/optimizely/index.tests.js
- Run prettier on files changed in https://github.com/optimizely/javascript-sdk/pull/418 so it's easier to review
=> refactor(core): Prettier prep for PR 418

packages/optimizely-sdk/CHANGELOG.MD, packages/optimizely-sdk/lib/index.browser.tests.js, packages/optimizely-sdk/lib/index.node.tests.js, packages/optimizely-sdk/lib/index.react_native.tests.js, packages/optimizely-sdk/lib/utils/enums/index.js, packages/optimizely-sdk/package-lock.json, packages/optimizely-sdk/package.json
- Bumps the version to `3.6.0-alpha.1`
- Updates changelog
=> chore(optimizely-sdk): Prepare for 3.6.0-alpha.1 release

packages/optimizely-sdk/lib/core/bucketer/index.tests.js, packages/optimizely-sdk/lib/core/decision_service/index.js, packages/optimizely-sdk/lib/core/decision_service/index.tests.js, packages/optimizely-sdk/lib/core/optimizely_config/index.tests.js, packages/optimizely-sdk/lib/core/project_config/index.js, packages/optimizely-sdk/lib/core/project_config/index.tests.js, packages/optimizely-sdk/lib/core/project_config/project_config_manager.tests.js, packages/optimizely-sdk/lib/index.browser.tests.js, packages/optimizely-sdk/lib/optimizely/index.tests.js, packages/optimizely-sdk/lib/utils/attributes_validator/index.js, packages/optimizely-sdk/lib/utils/fns/index.js, packages/optimizely-sdk/package-lock.json, packages/optimizely-sdk/package.json
To reduce package size, we are gradually removing lodash library. This PR removes `lodash.cloneDeep` from optimizely-sdk package. It is still part of the repository but it is only being used to run tests. lodash has been removed from dependencies and moved to dev-dependencies in package.json
All unit tests and Full Stack compatibility tests pass after this change
=> refactor: Removed dependency on lodash.cloneDeep

.travis.yml, packages/datafile-manager/__mocks__/@react-native-community/async-storage.ts, packages/datafile-manager/__test__/reactNativeAsyncStorageCache.spec.ts, packages/datafile-manager/package-lock.json, packages/datafile-manager/package.json, packages/datafile-manager/src/persistentKeyValueCache.ts, packages/datafile-manager/src/reactNativeAsyncStorageCache.ts
This is a Key Value Pair cache implementation for react native. This will be used when developing a Separate Datafile Manager for React native which will support datafile caching.
Added Unit Tests
=> feat: Key Value cache implementation for React Native

packages/optimizely-sdk/lib/index.react_native.js, packages/optimizely-sdk/lib/index.react_native.tests.js, packages/optimizely-sdk/lib/utils/enums/index.js, packages/optimizely-sdk/lib/utils/enums/index.tests.js
Added Two new client engine values to be sent in events.
Client Engine will be set to `react-native-js` when a react native application will use javascript sdk directly
Client Engine will be set to `react-native` when a react native application will use react sdk 
Client versions behave correctly without any change. Current behaviour is.
1. When a react native app uses javascript SDK directly, clientVersion will be the version of javascript SDK. Which means `react-native-js` goes with `clientVersion` of javascript SDK
2. When a react native app uses React SDK, clientVersion will be the version passed in by react SDK. This means `react-native` goes with `clientVersion` of react SDK. 
Made appropriate changes to already existing unit tests.
=> feat: Added React Native Client Engines to be sent in events

packages/datafile-manager/.eslintrc.js, packages/datafile-manager/src/backoffController.ts, packages/datafile-manager/src/browserDatafileManager.ts, packages/datafile-manager/src/browserRequest.ts, packages/datafile-manager/src/config.ts, packages/datafile-manager/src/datafileManager.ts, packages/datafile-manager/src/eventEmitter.ts, packages/datafile-manager/src/http.ts, packages/datafile-manager/src/httpPollingDatafileManager.ts, packages/datafile-manager/src/index.browser.ts, packages/datafile-manager/src/index.node.ts, packages/datafile-manager/src/index.react_native.ts, packages/datafile-manager/src/nodeDatafileManager.ts, packages/datafile-manager/src/nodeRequest.ts, packages/datafile-manager/src/persistentKeyValueCache.ts, packages/datafile-manager/src/reactNativeAsyncStorageCache.ts, packages/datafile-manager/src/reactNativeDatafileManager.ts
Apply Prettier formatting and fix all ESlint errors & warnings.
Existing Unit tests
=> chore(datafile manager): Fix ESLint warnings & errors, apply Prettier formatting

packages/datafile-manager/__test__/backoffController.spec.ts, packages/datafile-manager/__test__/browserDatafileManager.spec.ts, packages/datafile-manager/__test__/browserRequest.spec.ts, packages/datafile-manager/__test__/eventEmitter.spec.ts, packages/datafile-manager/__test__/httpPollingDatafileManager.spec.ts, packages/datafile-manager/__test__/nodeDatafileManager.spec.ts, packages/datafile-manager/__test__/nodeRequest.spec.ts, packages/datafile-manager/__test__/reactNativeAsyncStorageCache.spec.ts, packages/datafile-manager/__test__/testUtils.ts, packages/datafile-manager/package.json
- Lint and formatting fixes for datafile manager tests
- Update lint package.json script to run on test files
Existing tests
=> chore(datafile manager): Lint and formatting fixes for datafile manager tests

packages/optimizely-sdk/lib/core/project_config/index.js, packages/optimizely-sdk/lib/core/project_config/index.tests.js, packages/optimizely-sdk/lib/core/project_config/project_config_manager.js, packages/optimizely-sdk/lib/core/project_config/project_config_manager.tests.js, packages/optimizely-sdk/lib/index.browser.js, packages/optimizely-sdk/lib/index.browser.umdtests.js, packages/optimizely-sdk/lib/index.d.ts, packages/optimizely-sdk/lib/index.node.js, packages/optimizely-sdk/lib/index.react_native.js, packages/optimizely-sdk/lib/optimizely/index.js, packages/optimizely-sdk/lib/optimizely/index.tests.js
- Changed functionality of JSON schema validation by removing skipJSONValidation entirely.
Now user will need to import jsonSchemaValidator from @optimizely/optimizely-sdk/lib/utils/json_schema_validator and pass it to createInstance when validation is desired.
- Updated existing unit tests to reflect this change.
OASIS-6102
=> Change functionality of JSON schema validation by removing skipJSONValidation entirely.

packages/optimizely-sdk/lib/index.browser.tests.js, packages/optimizely-sdk/lib/index.browser.umdtests.js, packages/optimizely-sdk/lib/plugins/error_handler/index.js, packages/optimizely-sdk/lib/plugins/error_handler/index.tests.js, packages/optimizely-sdk/lib/plugins/event_dispatcher/index.browser.js, packages/optimizely-sdk/lib/plugins/event_dispatcher/index.browser.tests.js, packages/optimizely-sdk/lib/plugins/event_dispatcher/index.node.js, packages/optimizely-sdk/lib/plugins/event_dispatcher/index.node.tests.js, packages/optimizely-sdk/lib/plugins/logger/enums.js, packages/optimizely-sdk/lib/plugins/logger/index.js, packages/optimizely-sdk/lib/plugins/logger/index.react_native.js, packages/optimizely-sdk/lib/plugins/logger/index.react_native.tests.js, packages/optimizely-sdk/lib/plugins/logger/index.tests.js, packages/optimizely-sdk/rollup.config.js
This PR converts contents inside `lib/plugins` to ESModule.
All unit test and Full stack compatibility suite tests pass.
=> refactor: Convert lib/plugins from CJS to ES module

packages/optimizely-sdk/lib/core/decision_service/index.tests.js, packages/optimizely-sdk/lib/optimizely/index.js, packages/optimizely-sdk/lib/optimizely/index.tests.js, packages/optimizely-sdk/lib/tests/test_data.js, packages/optimizely-sdk/rollup.config.js
This PR only converts contents inside `lib/optimizely/*` and `lib/tests/*` to ESModule.
All unit test and Full stack compatibility suite tests pass
=> refactor: Convert lib/optimizely/* and lib/tests/* to ES module

packages/optimizely-sdk/lib/core/audience_evaluator/index.js, packages/optimizely-sdk/lib/core/audience_evaluator/index.tests.js, packages/optimizely-sdk/lib/core/bucketer/index.js, packages/optimizely-sdk/lib/core/bucketer/index.tests.js, packages/optimizely-sdk/lib/core/condition_tree_evaluator/index.js, packages/optimizely-sdk/lib/core/condition_tree_evaluator/index.tests.js, packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.js, packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.tests.js, packages/optimizely-sdk/lib/core/decision_service/index.js, packages/optimizely-sdk/lib/core/decision_service/index.tests.js
This converts these folders inside lib/core to ESModule.
lib/core/
→ audience_evaluator,
→ bucketer, 
→ condition_tree_evaluator, 
→ custom_attribute_condition_evaluator, 
→ decision_service
All unit test and Full stack compatibility suite tests pass.
=> refactor: Convert lib/core to ES module (Part 1/2)

packages/optimizely-sdk/lib/core/event_builder/event_helpers.js, packages/optimizely-sdk/lib/core/event_builder/event_helpers.tests.js, packages/optimizely-sdk/lib/core/event_builder/index.js, packages/optimizely-sdk/lib/core/event_builder/index.tests.js, packages/optimizely-sdk/lib/core/notification_center/index.js, packages/optimizely-sdk/lib/core/notification_center/index.tests.js, packages/optimizely-sdk/lib/core/optimizely_config/index.js, packages/optimizely-sdk/lib/core/optimizely_config/index.tests.js, packages/optimizely-sdk/lib/core/project_config/index.js, packages/optimizely-sdk/lib/core/project_config/index.tests.js, packages/optimizely-sdk/lib/core/project_config/project_config_manager.js, packages/optimizely-sdk/lib/core/project_config/project_config_manager.tests.js, packages/optimizely-sdk/lib/core/project_config/project_config_schema.js, packages/optimizely-sdk/lib/optimizely/index.js, packages/optimizely-sdk/lib/utils/json_schema_validator/index.js
This PR only converts contents inside lib/core to ESModule.
lib/core/
→ event_builder
→ notification_center,
→ optimizely_config
→ project_config
All unit test and Full stack compatibility suite tests are getting passed.
=> refactor: Convert lib/core to ES module (Part 2/2)

packages/optimizely-sdk/CHANGELOG.MD, packages/optimizely-sdk/rollup.config.js
Since all the code was common JS earlier, json schema validator could be imported directly from source code. Now its no longer possible because its converted to Es module. Created a separate Cjs bundle for json schema validator to serve the same purpose.
Manually tested thoroughly
=> refactor: Added a separate bundle for Json Schema Validator

packages/datafile-manager/package-lock.json, packages/datafile-manager/package.json
Datafile Manager declares `@react-native-community/async-storage` as a peer dependency. This is required to be in `node_modules` when typescript is transpiled before publishing or during development. Adding it as a dev dependency in addition to the peer dependency.
All the existing test pass
=> refactor: Added a dev dependency to datafile manager

packages/datafile-manager/README.md
Datafile Manager does not require manual installation of `@react-native-community/async-storage` dependency as this is now added as a dev dependency and will automatically be installed
Documentation change. Not testing needed.
=> chore: Removed unwanted step from datafile manager docs

packages/datafile-manager/package.json
Remove entry point for RN datafile manager.
Existing tests
=> chore(datafile manager): Remove react native entry point from package.json

packages/datafile-manager/CHANGELOG.md, packages/datafile-manager/package-lock.json, packages/datafile-manager/package.json
Prepare for js-sdk-datafile-manager 0.5.0 release
=> chore: Prepare for js-sdk-datafile-manager 0.5.0 release

packages/optimizely-sdk/lib/core/project_config/index.js, packages/optimizely-sdk/lib/core/project_config/index.tests.js, packages/optimizely-sdk/lib/optimizely/index.tests.js
`createProjectConfig` was destructively mutating its `datafile` argument. After that mutation, the datafile object could not be re-used to create another instance.
With this change, `createProjectConfig` copies the objects it needs to mutate and mutates only those copies. It's not a full deep clone; it only shallowly clones audiences, experiments, feature flags, groups, rollouts, group experiments, and rollout experiments.
- Updated & new unit tests
- Compatibility suite should pass
https://optimizely.atlassian.net/browse/OASIS-6301
=> fix(project config): Don't mutate the datafile object

packages/optimizely-sdk/rollup.config.js
Update Rollup build configuration to produce source maps for the minified .js files. This helps with debugging any SDK issues or usage.
Manually tested in Node, using [built-in debugger](https://nodejs.org/en/docs/guides/debugging-getting-started/) with Chrome dev tools
=> chore: Add source maps to build output

packages/optimizely-sdk/CHANGELOG.MD, packages/optimizely-sdk/README.md, packages/optimizely-sdk/lib/index.browser.tests.js, packages/optimizely-sdk/lib/index.node.tests.js, packages/optimizely-sdk/lib/index.react_native.tests.js, packages/optimizely-sdk/lib/utils/enums/index.js, packages/optimizely-sdk/package-lock.json, packages/optimizely-sdk/package.json
Prepare for 4.0.0-rc.2 release
=> chore: Prepare for 4.0.0-rc.2 release

packages/optimizely-sdk/CHANGELOG.MD, packages/optimizely-sdk/lib/index.browser.tests.js, packages/optimizely-sdk/lib/index.node.tests.js, packages/optimizely-sdk/lib/index.react_native.tests.js, packages/optimizely-sdk/lib/utils/enums/index.js, packages/optimizely-sdk/package-lock.json, packages/optimizely-sdk/package.json
=> chore: Prepare for 4.0.0 release

packages/optimizely-sdk/lib/core/decision_service/index.tests.js, packages/optimizely-sdk/lib/core/optimizely_config/index.tests.js, packages/optimizely-sdk/lib/core/project_config/index.js, packages/optimizely-sdk/lib/core/project_config/index.tests.js, packages/optimizely-sdk/lib/optimizely/index.js, packages/optimizely-sdk/lib/optimizely/index.tests.js, packages/optimizely-sdk/lib/tests/test_data.js, packages/optimizely-sdk/lib/utils/enums/index.js
Implemented getFeatureVariableJson API
Added unit tests for getFeatureVariableJson.
=> feat: Added a new getFeatureVariableJson Api

packages/optimizely-sdk/lib/index.d.ts, packages/optimizely-sdk/lib/optimizely/index.js, packages/optimizely-sdk/lib/optimizely/index.tests.js, packages/optimizely-sdk/lib/utils/enums/index.js
Implemented getAllFeatureVariables API
Added new unit tests.
=> feat: Added a new getAllFeatureVariables Api

packages/datafile-manager/package.json, packages/optimizely-sdk/package.json
The version spec in package.json#engines.node is out of date from what is specified in the corresponding READMEs. This updates the package to declare the correct minimum version of node.
While it may seem unimportant, the package.json#engines.node spec is respected by some tools, like nodenv, for node version selection. So this being incorrect can potentially activate the wrong version of node for someone developing locally.
=> Updates engines.node stanza to reflect actual requirements

packages/datafile-manager/package.json, packages/event-processor/package.json, packages/logging/package.json, packages/optimizely-sdk/package.json, packages/utils/package.json
Configure each package's `package.json#repository.directory` 
property to properly reflect the location of the package within 
the repository.
This is the standard configuration value for deep-linking into a
package's directory within a monorepo.
npm RFC: https://github.com/npm/rfcs/blob/latest/implemented/0010-monorepo-subdirectory-declaration.md
This will ensure the packages' pages on npmjs.org will link to the
correct directory.
Also, _eventually_, it will ensure the `npm repo` command opens to the
correct location: https://github.com/npm/cli/pull/163
Lastly, this is _required_ for monorepo packages to be successfully
published to the GitHub Package Registry (if that is ever considered in
the future).
https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem …
=> Configure repository.directory for monorepo packages

packages/optimizely-sdk/README.md, packages/optimizely-sdk/lib/core/event_builder/index.tests.js, packages/optimizely-sdk/lib/optimizely/index.tests.js, packages/optimizely-sdk/lib/utils/fns/index.js, packages/optimizely-sdk/package.json, packages/utils/src/index.ts
UUID is already exposed in the js-sdk-utils package, so we should use it directly.
That will ensure de-duping, as well as automatic tree shaking of the uuid dep (because the utils package imports UUID via ESM).
**Before**
**After**
closes #479
=> Removes direct UUID dep

packages/optimizely-sdk/CHANGELOG.MD, packages/optimizely-sdk/lib/index.d.ts
- Add missing definition for `getFeatureVariable`
- Fix return type for `getAllFeatureVariables`
Manually tested
=> fix: Add type definition for getFeatureVariable, fix type definition for getAllFeatureVariables

packages/optimizely-sdk/lib/index.browser.tests.js, packages/optimizely-sdk/lib/index.browser.umdtests.js, packages/optimizely-sdk/lib/index.react_native.tests.js, packages/optimizely-sdk/lib/plugins/event_dispatcher/index.browser.tests.js
Fixes cross-test pollution of global XHR object.
The global XHR object was being stubbed in some tests but not others. But the tests that didn't stub weren't failing because the tests that _were_ stubbing weren't being cleaned up! So some test suites were depending (implicitly) on side effects from other test files.
partially fixes #488
=> Fix test stubbings of global XHR object

packages/optimizely-sdk/lib/index.browser.tests.js, packages/optimizely-sdk/lib/index.react_native.tests.js, packages/optimizely-sdk/lib/optimizely/index.tests.js, packages/optimizely-sdk/lib/plugins/event_dispatcher/index.node.tests.js, packages/optimizely-sdk/package.json
- Several unit tests weren't properly stubbing the default event dispatcher - add these stubs
- The test suite wasn't exiting due to active timers not being cleaned up. Fixed this by mocking `setTimeout` using `sinon.useFakeTimers`
- One test for Node default event dispatcher was relying on a real connection error from attempting to request to an invalid domain. Added a `nock` mock for this to prevent the real request.
Run `npm test`. Should exit immediately, and not make any outgoing HTTP requests.
https://github.com/optimizely/javascript-sdk/issues/487
=> fix: Stub event dispatcher and mock timers in tests

packages/datafile-manager/CHANGELOG.md, packages/datafile-manager/__test__/nodeDatafileManager.spec.ts, packages/datafile-manager/src/config.ts, packages/datafile-manager/src/datafileManager.ts, packages/datafile-manager/src/nodeDatafileManager.ts
Added support for Authenticated Datafiles
Will Add Unit Tests.
=> feat: Added support for Authenticated Datafiles

packages/optimizely-sdk/CHANGELOG.MD, packages/optimizely-sdk/lib/core/audience_evaluator/index.js
Updating audience evaluation log level to be debug. The only info level log will be the one corresponding to the result of overall evaluation of an audience.
All checks pass.
=> fix(log-level) change single audience result to debug

packages/optimizely-sdk/CHANGELOG.MD, packages/optimizely-sdk/lib/index.d.ts, packages/optimizely-sdk/package-lock.json, packages/optimizely-sdk/package.json
Bump `datafile-manager` version to `0.6.0`. This adds support for private datafiles for Node.
- Unit tests added in the `datafile-manager` package along with the implementation.
- Full Stack Compat Suite tests will be added to explicitly test this feature.
=> feat: Bump Datafile Manager version

packages/utils/CHANGELOG.MD, packages/utils/__mocks__/@react-native-community/async-storage.ts, packages/utils/__tests__/reactNativeAsyncStorageCache.spec.ts, packages/utils/package-lock.json, packages/utils/package.json, packages/utils/src/index.ts, packages/utils/src/persistentKeyValueCache.ts, packages/utils/src/reactNativeAsyncStorageCache.ts
This is first PR in an effort to implement support for Offline Events persistence for React Native Apps. Async Storage implementation was already done in `datafile-manager` package to support datafile caching. This PR moves the generic caching implementation to `utils` so that it can be used by both `datafile-manager` and `event-processor`.
All Existing tests should pass
=> refactor: Move Async Storage Implementation to utils package

packages/utils/src/index.ts
`ReactNativeAsyncStorageCache` and `PersistentKeyValueCache` both are exported as default. They were exported as default from `index` too which did not work and was incorrect even if it worked. modified them to be exported as named from `index`. 
Unit tests should pass
=> fix: Fixed incorrectly exported classes in utils

packages/utils/src/index.ts
Reverts part of a prior change in the utils package for two reasons:
- `uuid.v4` has different behavior when passed arguments. We have no use for this behavior, thus it is better to ensure no arguments are accidentally passed.
- We don't want our type definitions to be dependent on `'uuid'`'s type definitions
Existing tests
=> fix(utils): Wrap uuid.v4 to disallow passing extra arguments and prevent dependency on uuid package types

packages/optimizely-sdk/README.md
This was removed along with the change to use the uuid function exported by the utils package. But, we are listing all additional code from transitive dependencies here (for example, decompress-response), not just direct dependencies.
None. Docs-only change.
=> docs(readme): Restore uuid in Additional code section

packages/optimizely-sdk/CHANGELOG.MD, packages/optimizely-sdk/lib/index.d.ts, packages/optimizely-sdk/lib/optimizely/index.js, packages/optimizely-sdk/lib/optimizely/index.tests.js
- fixed case for getFeatureVariableJSON api
- Instead of adding another check for apiName to the generic `_getFeatureVariableForType` function, Moved invalid instance check and log message to their own functions. 
All unit tests FSC tests should pass
=> fix: Changed getFeatureVariableJson to getFeatureVariableJSON

packages/optimizely-sdk/CHANGELOG.MD, packages/optimizely-sdk/lib/index.browser.tests.js, packages/optimizely-sdk/lib/index.node.tests.js, packages/optimizely-sdk/lib/index.react_native.tests.js, packages/optimizely-sdk/lib/utils/enums/index.js, packages/optimizely-sdk/package-lock.json, packages/optimizely-sdk/package.json
=> chore: Prepare for 4.1.0 release

.travis.yml
Adds a separate stage for Source Clear, to only run on cron builds.
Manually need to see when cron is running this stage.
OASIS-6817
=> ci: add source clear as a separate stage;

packages/optimizely-sdk/lib/optimizely/index.js, packages/optimizely-sdk/lib/utils/user_profile_service_validator/index.ts
Convert `user_profile_service_validator` module from JS to TS.
- Manual testing using local build and linked Node app
=> feat: Convert user_profile_service_validator module to TS

packages/event-processor/package-lock.json, packages/event-processor/package.json
Typescript version was updated which resulted in some problems with stubbing event processor. Reverted back to the version which was being used earlier.
Tested by locally linking this version of event processor with optimizely sdk and verified that stubbing works correctly after this fix.
=> fix: Event Processor - Reverted back the typescript version to fix stubbing issue

packages/optimizely-sdk/lib/index.browser.tests.js, packages/optimizely-sdk/lib/index.node.tests.js, packages/optimizely-sdk/lib/index.react_native.js, packages/optimizely-sdk/lib/index.react_native.tests.js, packages/optimizely-sdk/lib/optimizely/index.js, packages/optimizely-sdk/lib/optimizely/index.tests.js, packages/optimizely-sdk/lib/plugins/event_dispatcher/index.browser.js, packages/optimizely-sdk/package-lock.json, packages/optimizely-sdk/package.json
Integrated the newly released event processor package which implements react native event processor to support offline storage of events.
1. All Unit tests should pass
2. All FSC tests should pass
=> feat: Integrate react native event processor with optimizely SDK

packages/optimizely-sdk/lib/core/bucketer/index.js, packages/optimizely-sdk/lib/core/bucketer/index.tests.js, packages/optimizely-sdk/lib/core/decision_service/index.js, packages/optimizely-sdk/lib/core/decision_service/index.tests.js, packages/optimizely-sdk/lib/optimizely/index.js, packages/optimizely-sdk/lib/optimizely/index.tests.js, packages/optimizely-sdk/lib/utils/enums/index.js
With this change we are introducing targeted rollout specific log messages.
All Unit and FSC Tests are getting passed
=> fix(logs): Fixing log messages for Targeted Rollouts

packages/optimizely-sdk/README.md
Adding readme language to clarify that there are downsides to installing via unpkg and it should not be our default recommended method. 
Just need feedback on language/framing
=> docs: Update README.md description of unpkg snippet installation

packages/utils/CHANGELOG.MD, packages/utils/package-lock.json, packages/utils/package.json
=> chore(utils): Prepare for js-sdk-utils v0.4.0 release

packages/optimizely-sdk/lib/optimizely/index.js, packages/optimizely-sdk/lib/utils/event_tags_validator/index.ts, packages/optimizely-sdk/lib/utils/user_profile_service_validator/index.ts
- Convert `event_tags_validator` module from JS to TS
- Revise `user_profile_service_validator` module
=> feat: Convert event_tags_validator module to TS

packages/optimizely-sdk/lib/core/decision_service/index.tests.js, packages/optimizely-sdk/lib/core/project_config/project_config_manager.tests.js, packages/optimizely-sdk/lib/core/project_config/project_config_schema.ts, packages/optimizely-sdk/lib/optimizely/index.tests.js, packages/optimizely-sdk/lib/utils/json_schema_validator/index.ts
Convert `project_config_schema` and `json_schema_validator` modules from JS to TS.
- Manual testing using local build and linked Node app
=> feat: Convert project_config_schema and json_schema_validator modules to TS

packages/optimizely-sdk/lib/core/event_builder/event_helpers.js, packages/optimizely-sdk/lib/core/event_builder/index.js, packages/optimizely-sdk/lib/utils/attributes_validator/index.tests.js, packages/optimizely-sdk/lib/utils/attributes_validator/index.ts
Convert `attributes_validator` module from JS to TS.
=> feat: Convert attributes_validator to TS

packages/optimizely-sdk/lib/utils/json_schema_validator/index.ts
To avoid using the `{}` type, change `json_schema_validator.validate` to use a type guard above that will return early when the argument doesn't match that type.
Existing tests
=> fix(json schema validator): Replace {} type assertion with type guard

packages/optimizely-sdk/lib/core/event_builder/event_helpers.js, packages/optimizely-sdk/lib/core/event_builder/index.js, packages/optimizely-sdk/lib/utils/event_tag_utils/index.tests.js, packages/optimizely-sdk/lib/utils/event_tag_utils/index.ts
- Convert `event_tag_utils` module from JS to TS.
=> feat: Convert event_tag_utils module to TS

packages/datafile-manager/CHANGELOG.md, packages/datafile-manager/__test__/httpPollingDatafileManager.spec.ts, packages/datafile-manager/__test__/reactNativeAsyncStorageCache.spec.ts, packages/datafile-manager/src/datafileManager.ts, packages/datafile-manager/src/httpPollingDatafileManager.ts, packages/datafile-manager/src/persistentKeyValueCache.ts, packages/datafile-manager/src/reactNativeAsyncStorageCache.ts, packages/datafile-manager/src/reactNativeDatafileManager.ts
Summary
----------
- Modified datafileManager and httpPollingDatafileManager to use datafile strings
- Removed unneeded JSON parsing of response body
Test Plan
----------
- Modified existing datafile manager tests to account for new changes to datafile variable type
=> feat: modify datafile managers to use datafile strings instead of objects

packages/optimizely-sdk/lib/core/bucketer/index.js, packages/optimizely-sdk/lib/core/bucketer/index.tests.js
Fix an issue introduced in https://github.com/optimizely/javascript-sdk/pull/515. When `bucket` returns empty string, we shouldn't log a warning about invalid variation ID. Empty string is a valid value for the `entityId` property of traffic allocation range objects. There is no invalid variation ID in this situation.
Manually tested with A/B tests and rollouts. Added new unit test.
OASIS-6890
=> fix(bucketer): Don't log invalid variation ID warning when bucketed into traffic allocation range with empty string entityId

.travis.yml
Prior to running Source Clear build step, change into optimizely-sdk directory
N/A
=> fix: Change to optimizely-sdk directory prior to running Source Clear

packages/optimizely-sdk/lib/index.d.ts
Add new datafile accessor method to TS type definitions
Manually tested with `npm link` and local app
=> fix(datafile accessor): Add datafile accessor method to TS definitions

packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.tests.js, packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.ts, packages/optimizely-sdk/lib/utils/enums/index.ts, packages/optimizely-sdk/lib/utils/semantic_version/index.tests.js, packages/optimizely-sdk/lib/utils/semantic_version/index.ts
- Semantic version added
- Greater than or equal (ge) and less than or equal (le) evaluator added
- All relevant test cases added
=> feat: semver implementation

packages/optimizely-sdk/lib/core/decision_service/index.d.ts, packages/optimizely-sdk/lib/index.d.ts, packages/optimizely-sdk/lib/shared_types.ts
Create `index.d.ts` file for decision_service module
=> feat: Create index.d.ts file for decision_service

packages/optimizely-sdk/lib/core/project_config/project_config_manager.d.ts, packages/optimizely-sdk/lib/index.d.ts, packages/optimizely-sdk/lib/shared_types.ts
- Added `project_config_manager` interface
=> feat: Added project_config_manager interface

packages/optimizely-sdk/CHANGELOG.MD, packages/optimizely-sdk/lib/index.browser.tests.js, packages/optimizely-sdk/lib/index.d.ts, packages/optimizely-sdk/lib/index.node.tests.js, packages/optimizely-sdk/lib/index.react_native.tests.js, packages/optimizely-sdk/lib/utils/enums/index.ts, packages/optimizely-sdk/package-lock.json, packages/optimizely-sdk/package.json
- Added missing `OptimizelyConfig` interface and `UserAttributes` type definitions to TS type definitions required by react-sdk
- Prepare for releasing 4.3.1
=> chore: Export OptimizelyConfig interface and UserAttributes type Definitions from TS type definitions and prepare for release 4.3.1

packages/optimizely-sdk/lib/core/audience_evaluator/index.tests.js, packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.tests.js
Remove `console.log` calls that are cluttering the test output.
Run tests
=> chore: Remove console.log statements from tests

packages/optimizely-sdk/CHANGELOG.MD, packages/optimizely-sdk/lib/core/project_config/project_config_manager.js, packages/optimizely-sdk/lib/core/project_config/project_config_manager.tests.js
Fixes a regression introduced during refactoring for datafile accessor - any time the `datafile` property of the object passed to `createInstance` is missing or falsy, the logger will output (for example):
```
[OPTIMIZELY] - ERROR 2020-10-05T23:38:15.224Z CONFIG_VALIDATOR: No datafile specified. Cannot start optimizely
```
Passing in an `sdkKey`, but no `datafile`, is valid and supported when calling `createInstance`, but this message leads the user to believe otherwise. In this situation, nothing is actually wrong, but the message says "Cannot start optimizely".
To fix, in `ProjectConfigManager` `__initialize`, when `config.datafile` is falsy, we do not call `__handleNewDatafile`, avoiding the code path that eventually would log the error message.
- Added new unit test
- Manually tested
=> fix(project config manager): Don't log an error when not initialized with datafile

packages/optimizely-sdk/lib/index.d.ts
`UserProfileService` and several other types were removed by mistake from lib/index.d.ts. 
Manual testing
https://github.com/optimizely/javascript-sdk/issues/593
=> fix(TS type defs): Restore missing types

packages/optimizely-sdk/.eslintrc.js, packages/optimizely-sdk/lib/core/audience_evaluator/index.js, packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.ts, packages/optimizely-sdk/lib/core/decision_service/index.js, packages/optimizely-sdk/lib/core/event_builder/event_helpers.js, packages/optimizely-sdk/lib/core/event_builder/event_helpers.tests.js, packages/optimizely-sdk/lib/core/event_builder/index.js, packages/optimizely-sdk/lib/core/event_builder/index.tests.js, packages/optimizely-sdk/lib/core/project_config/index.js, packages/optimizely-sdk/lib/core/project_config/index.tests.js, packages/optimizely-sdk/lib/core/project_config/project_config_manager.js, packages/optimizely-sdk/lib/index.browser.js, packages/optimizely-sdk/lib/index.node.js, packages/optimizely-sdk/lib/index.react_native.js, packages/optimizely-sdk/lib/optimizely/index.tests.js, packages/optimizely-sdk/lib/optimizely/index.ts, packages/optimizely-sdk/lib/utils/attributes_validator/index.ts, packages/optimizely-sdk/lib/utils/event_processor_config_validator/index.ts, packages/optimizely-sdk/lib/utils/fns/index.tests.js, packages/optimizely-sdk/lib/utils/fns/index.ts, packages/optimizely-sdk/package-lock.json, packages/optimizely-sdk/package.json
- Upgrade TypeScript in `optimizely-sdk` package to v4.0.3
- Use default export object for `fns` module to avoid stubbing issue that came out after the upgrade
=> feat: Upgrade TypeScript to v4.0.3 in optimizely-sdk package

packages/event-processor/package-lock.json, packages/event-processor/package.json
- Upgrade TypeScript in `event-processor` package to v4.0.3
=> feat: Upgrade TypeScript to v4.0.3 in event-processor

packages/optimizely-sdk/lib/index.browser.ts, packages/optimizely-sdk/lib/index.d.ts, packages/optimizely-sdk/lib/index.node.ts, packages/optimizely-sdk/lib/index.react_native.ts, packages/optimizely-sdk/lib/optimizely/index.ts, packages/optimizely-sdk/lib/shared_types.ts, packages/optimizely-sdk/rollup.config.js
- Converted `packages\optimizely-sdk\lib\index.node.js` to TS
- Converted `packages\optimizely-sdk\lib\index.browser.js` to TS
- Converted `packages\optimizely-sdk\lib\index.react_native.js` to TS
- All existing unit tests should pass
- All existing test cases on FSC should pass
=> converted entry level modules to ts

packages/optimizely-sdk/lib/core/event_processor/index.ts
- Allow using `--isolatedModules` flag in tsconfig by fixing exports in event_processor
FSC and unit tests
[SDK-issue 609](https://github.com/optimizely/javascript-sdk/issues/609)
=> fix: Allow using --isolatedModules flag in tsconfig by fixing exports in event_processor

packages/event-processor/__tests__/buildEventV1.spec.ts, packages/event-processor/__tests__/v1EventProcessor.react_native.spec.ts, packages/event-processor/__tests__/v1EventProcessor.spec.ts, packages/event-processor/src/events.ts, packages/event-processor/src/v1/buildEventV1.ts
- add `enabled` field to decision metadata object
Unit tests
[OASIS-7346](https://optimizely.atlassian.net/browse/OASIS-7346)
=> feat: Add enabled to decision metadata in event processor

packages/optimizely-sdk/CHANGELOG.MD, packages/optimizely-sdk/lib/optimizely/index.ts
Fix for #622 . For the Node.js version of `setTimeout`, the return value isn't `number`, but `Timeout`. To allow this to typecheck regardless of whether the browser or Node.js version is used, set the type of `readyTimeout` to `any`.
Existing tests
#622
=> fix(Optimizely): Use any type for return value of setTimeout

packages/event-processor/__tests__/pendingEventsStore.spec.ts, packages/logging/src/logger.ts, packages/optimizely-sdk/lib/optimizely/index.ts, packages/optimizely-sdk/lib/shared_types.ts, packages/optimizely-sdk/lib/utils/attributes_validator/index.ts, packages/optimizely-sdk/lib/utils/config_validator/index.ts, packages/optimizely-sdk/lib/utils/fns/index.ts, packages/optimizely-sdk/lib/utils/user_profile_service_validator/index.ts, tsconfig.json
This pr created in response to sdk issue https://github.com/optimizely/javascript-sdk/issues/613
The steps to reproduce and fix the issues were:
- comment out`"suppressImplicitAnyIndexErrors": true` in TSConfig
- fix type error issues as shown below.
Existing FSC and unit tests
=> fix: exclude suppressImplicitAnyIndexErrors from tsconfig and fix type errors

packages/optimizely-sdk/CHANGELOG.MD, packages/optimizely-sdk/lib/index.d.ts, packages/optimizely-sdk/lib/shared_types.ts
Allow `logLevel` to support string type in addition to LogLevel enum to avoid compiler type error 
[SDK-issue 614](https://github.com/optimizely/javascript-sdk/issues/614)
=> fix: Allow logLevel to support string type to avoid compiler type error

packages/optimizely-sdk/CHANGELOG.MD, packages/optimizely-sdk/lib/index.d.ts, packages/optimizely-sdk/lib/optimizely/index.ts, packages/optimizely-sdk/lib/shared_types.ts
- Move `OptimizelyOptions` interface to `shared_types` to provide isolation from internal ts modules
=> fix: Move OptimizelyOptions interface to shared_types

packages/optimizely-sdk/lib/core/decision_service/index.tests.js, packages/optimizely-sdk/lib/optimizely/index.tests.js, packages/optimizely-sdk/lib/optimizely/index.ts, packages/optimizely-sdk/lib/optimizely_user_context/index.tests.js, packages/optimizely-sdk/lib/optimizely_user_context/index.ts, packages/optimizely-sdk/lib/tests/test_data.js, packages/optimizely-sdk/lib/utils/enums/index.ts
- Implemented `createUserContext` in optimizely client
- Created `OptimizelyUserContext` class and implement `setAttribute` method
- Cleaned up existing unit tests
- Included `decideConfig` for future decide API testing
- Manual testing + unit tests
- [OASIS-6942](https://optimizely.atlassian.net/browse/OASIS-6942)
=> feat: Implement createUserContext for decide API

packages/optimizely-sdk/lib/optimizely/index.tests.js, packages/optimizely-sdk/lib/optimizely/index.ts, packages/optimizely-sdk/lib/optimizely_user_context/index.tests.js, packages/optimizely-sdk/lib/optimizely_user_context/index.ts
- Implemented `decideAll` and `decideForKeys`
- Manual testing + unit tests
- [OASIS-6944](https://optimizely.atlassian.net/browse/OASIS-6944)
=> feat: Implement decideAll api

packages/optimizely-sdk/lib/index.browser.ts, packages/optimizely-sdk/lib/index.d.ts, packages/optimizely-sdk/lib/index.node.ts, packages/optimizely-sdk/lib/index.react_native.ts
The `OptimizelyDecideOptions` enum was being exported as a type. Correctly exported it as enum and added declaration to typings.
1. Unit tests pass.
2. Full stack Compatibility suite tests pass.
=> refactor: Correctly exported OptimizelyDecideOptions enum

packages/optimizely-sdk/lib/optimizely_decision/index.ts, packages/optimizely-sdk/lib/optimizely_user_context/index.ts
The OptimizelyUserContext instance is returned as a part of decision at the end of the decide api call. If the instance is not cloned at the beginning, it may have different states than one used for the decision.
In this pr, cloning of user context is implemented before calling decide api.
Unit tests + Manual testing
- [OASIS-2700](https://optimizely.atlassian.net/browse/OASIS-7400)
=> feat: Clone OptimizelyUserContext before calling decide api

packages/optimizely-sdk/lib/core/decision_service/index.d.ts, packages/optimizely-sdk/lib/core/decision_service/index.js, packages/optimizely-sdk/lib/core/decision_service/index.tests.js, packages/optimizely-sdk/lib/optimizely/index.tests.js, packages/optimizely-sdk/lib/optimizely/index.ts
- Implemented IGNORE_USER_PROFILE_SERVICE flag in decide options
- Fixed affected unit tests
- Added unit test coverage with IGNORE_USER_PROFILE_SERVICE decide option
- Manual Testing
This pr is to be finalized once https://github.com/optimizely/javascript-sdk/pull/640 is merged
=> feat: Implement IGNORE_USER_PROFILE_SERVICE flag in decide options

packages/optimizely-sdk/lib/core/decision_service/index.js, packages/optimizely-sdk/lib/index.browser.ts, packages/optimizely-sdk/lib/index.d.ts, packages/optimizely-sdk/lib/index.node.ts, packages/optimizely-sdk/lib/index.react_native.ts, packages/optimizely-sdk/lib/optimizely/index.tests.js, packages/optimizely-sdk/lib/optimizely/index.ts, packages/optimizely-sdk/lib/optimizely_user_context/index.ts, packages/optimizely-sdk/lib/shared_types.ts
- This pr changes `variationKey` and `ruleKey` from empty string to `null`  in a rollout `decisionInfo` payload in order to pass FSC tests.
- Changed `OptimizelyDecideOptions` enums to `OptimizelyDecideOption` to be consistent with other SDKs.
- Unit tests
- [FSC tests](https://travis-ci.com/github/optimizely/fullstack-sdk-compatibility-suite/builds/213362981) with `uzair/decide-api-endpoints` testapp branch - all pass except for DECIDE WORLD tests, which will be addressed separately
=> fix: Change experimentKey and variationKey to be null in rollout in decisionInfo payload

packages/optimizely-sdk/lib/shared_types.ts
- `defaultDecideOptions` in SDKOption type added.
- All testcases including `@DEFAULT_DECIDE_OPTIONS` should pass.
=> feat: defaultDecideOptions in SDKOptions

packages/optimizely-sdk/lib/index.d.ts, packages/optimizely-sdk/lib/optimizely/index.ts, packages/optimizely-sdk/lib/optimizely_decision/index.ts, packages/optimizely-sdk/lib/optimizely_user_context/index.ts, packages/optimizely-sdk/lib/shared_types.ts
To prevent users from compiling our TS source files, the type definitions file `index.d.ts` has been updated to exclude imports from our source files (`OptimizelyUserContext` and `OptimizelyDecision`).
=> fix: Fix type definitions to avoid compiling source files

packages/event-processor/CHANGELOG.MD, packages/event-processor/__tests__/buildEventV1.spec.ts, packages/event-processor/src/events.ts
- Update `ConversionEvent` interface to allow event `id` type `null` and `tags` type `undefined`
The "why", or other context.
- Existing unit tests + added new tests
=> fix:(event processor): Update ConversionEvent interface 

packages/optimizely-sdk/lib/core/optimizely_config/index.tests.js, packages/optimizely-sdk/lib/core/optimizely_config/index.ts, packages/optimizely-sdk/lib/core/project_config/index.tests.js, packages/optimizely-sdk/lib/core/project_config/index.ts, packages/optimizely-sdk/lib/shared_types.ts, packages/optimizely-sdk/lib/tests/test_data.js
-  Added support for `sdkKey` and `environmentKey` in datafile, ProjectConfig, and OptimizelyConfig.
Existing unit tests + new tests + FSC
=> feat: Added support for sdkKey and environmentKey in OptimizelyConfig

packages/optimizely-sdk/lib/core/bucketer/index.tests.js, packages/optimizely-sdk/lib/core/bucketer/index.ts, packages/optimizely-sdk/lib/core/decision_service/index.tests.js, packages/optimizely-sdk/lib/core/decision_service/index.ts, packages/optimizely-sdk/lib/core/project_config/index.tests.js, packages/optimizely-sdk/lib/core/project_config/index.ts, packages/optimizely-sdk/lib/optimizely/index.ts, packages/optimizely-sdk/lib/shared_types.ts, packages/optimizely-sdk/lib/utils/fns/index.ts
JS sdk implements `experimentKeyMap` to store all experiments in projectConfig and uses it for experiment object lookup. This leads in accessing incorrect experiment object and serving incorrect variation in cases where project consists of multiple flags with same key rules as only one of those rules are getting stored in `experimentKeyMap`.
1. Use `experimentIdMap` to look up experiment object by experimentId in `bucket` method of bucketer module.
2. Pass experiment object instead of experimentKey in `getVariation`, `checkIfUserIsInAudience`, and `buildBucketerParams` of decision_service module.  
- Existing unit tests + local bundle + fsc.
- New fsc test cases run:
- node: https://travis-ci.com/github/optimizely/fullstack-sdk-compatibility-suite/builds/232167514
- browser: …
=> fix: Serve correct variation when rule keys are not unique for flags in a project

packages/optimizely-sdk/lib/core/project_config/index.ts, packages/optimizely-sdk/lib/shared_types.ts
Use enum to define type in getTypeCastValue in project_config
=> feat: Use enum to define type in getTypeCastValue

packages/optimizely-sdk/lib/core/condition_tree_evaluator/index.ts, packages/optimizely-sdk/lib/core/optimizely_config/index.tests.js, packages/optimizely-sdk/lib/core/optimizely_config/index.ts, packages/optimizely-sdk/lib/core/project_config/index.ts, packages/optimizely-sdk/lib/shared_types.ts, packages/optimizely-sdk/lib/tests/test_data.js
The following new public properties are added to OptimizelyConfig:
- sdkKey
- environmentKey
- attributes
- audiences
- events
- experimentRules and deliveryRules to OptimizelyFeature
- audiences to OptimizelyExperiment
All FSC tests OPTIMIZELY_CONFIG_V2 tests should pass.
FSC OptimizelyConfig [link](https://app.travis-ci.com/github/optimizely/fullstack-sdk-compatibility-suite/builds/235034135)
=> feat(OptimizelyConfig): Add new fields to OptimizelyConfig 

packages/optimizely-sdk/lib/core/optimizely_config/index.ts
- Fix order of  experiments inside `featuresMap` in `OptimizelyConfig` to match the order of `experimentIds` in datafile.
Unit tests + FSC + local bundle
=> fix: follow experimentIds order of experiments inside featuresMap of OptimizelyConfig

packages/optimizely-sdk/CHANGELOG.MD
- add a deprecation note (`OptimizelyFeature:experimentsMap`) to Changelog
=> chore: add OptimizelyConfig deprecation note to changelog

packages/optimizely-sdk/lib/core/project_config/project_config_manager.tests.js, packages/optimizely-sdk/lib/core/project_config/project_config_manager.ts
`OptimizelyConfig` object is created during initialization of `Optimizely` Instance. This almost doubles the initialization time for the SDK. This PR moves the creation of `OptimizelyConfig` object to `getOptimizelyConfig`. The `OptimizelyConfig` object will be created and cached when the `getOptimizelyConfig` API is called for the first time after every data file update.
- Manually tested thoroughly
- Updated unit tests
- All FSC test pass
=> Removed OptimizelyConfig creation from SDK initialization to reduce intialization time

packages/event-processor/CHANGELOG.MD, packages/event-processor/__tests__/buildEventV1.spec.ts, packages/event-processor/package-lock.json, packages/event-processor/package.json, packages/event-processor/src/v1/buildEventV1.ts
- experimentId and variationId should be empty if no variation or experiment is found.
- Manually tested
- All tests pass
=> fix: impression event attributes exp, var should be empty instead of null

packages/optimizely-sdk/package-lock.json, packages/optimizely-sdk/package.json
Updated the version of the lib json-schema
There is a vulnerability which was fixed in version 0.4.0 
Prototype Pollution  https://snyk.io/vuln/SNYK-JS-JSONSCHEMA-1920922
=> build(json-schema): update version to remove high-severity

packages/optimizely-sdk/lib/optimizely_user_context/index.tests.js, packages/optimizely-sdk/lib/optimizely_user_context/index.ts
- Remove config-ready check from forced-decision apis
- Unit and FSC tests
=> fix(ForcedDecision): remove config-ready check from forced-decision apis

packages/optimizely-sdk/CHANGELOG.MD
- Add a note about old bug-fix for forced-variation in exclusion group experiments
- OASIS-8051
=> chore: update CHANGELOG for forced-variation in exclusion group experiments

packages/optimizely-sdk/lib/core/decision_service/index.ts, packages/optimizely-sdk/lib/core/project_config/index.ts, packages/optimizely-sdk/lib/optimizely/index.ts, packages/optimizely-sdk/lib/optimizely_user_context/index.tests.js, packages/optimizely-sdk/lib/optimizely_user_context/index.ts, packages/optimizely-sdk/lib/shared_types.ts
- Checking variation in flagvariation map for forced decision
=> fix: Checking variation in flagvariation map instead of checking it only in experiment

packages/optimizely-sdk/lib/shared_types.ts
`4.9.0` introduced a typescript compilation issue due to an unused import. This PR fixes that.
All unit, cross browser and full stack compatibility tests pass.
"Fixes #732"
=> fix: Fixed typescript compilation issue introduced by `4.9.0`

packages/datafile-manager/package-lock.json, packages/datafile-manager/package.json, packages/event-processor/package-lock.json, packages/event-processor/package.json
Made the following dependencies optional in `datafile-manager` and `event-processor` packages.
`@react-native-community/async-storage`
`@react-native-community/netinfo`
- Manually tested thoroughly
- All tests pass
=> refactor: Made react native dependencies optional

packages/datafile-manager/CHANGELOG.md, packages/datafile-manager/package-lock.json, packages/datafile-manager/package.json, packages/event-processor/CHANGELOG.MD, packages/event-processor/package-lock.json, packages/event-processor/package.json
React native dependencies were converted from `peer` to `optional` in `js-sd-datafile-manager` version `0.9.2` and `js-sdk-event-processor` version `0.9.3`. After releasing, it appeared that they did not work as expected. This PR reverts back that change which was made in #735 and updates changelog and npm version to make new releases for both the packages.
- Manually tested.
- All unit tests pass
=> revert #735 and prep for release 0.9.3 for `js-sdk-datafile-manager` and 0.9.4 for `js-sdk-event-processor`

packages/datafile-manager/CHANGELOG.md, packages/datafile-manager/package.json, packages/event-processor/CHANGELOG.MD, packages/event-processor/package.json
Made the following peer dependencies optional in `datafile-manager` and `event-processor` packages.
`@react-native-community/async-storage`
`@react-native-community/netinfo`
- Manually tested thoroughly
- All tests pass
=> fix: made React Native peer dependencies optional and prep for release `0.9.4` for `js-sdk-datafile-manager` and `0.9.5` for `js-sdk-event-processor`

packages/optimizely-sdk/package.json
This PR is copied from [484](https://github.com/optimizely/javascript-sdk/pull/484). It was contributed by @jasonkarns a couple of years ago. I just pulled his changes, merged master and resolved conflicts.
ESM entrypoints are very very likely to be consumed by bundlers, not loaded directly into browsers. Therefore it is preferable that the bundlers have access to the unminified source so that consumers can have more control over the final output.
~~This change _adds_ an ESM output bundle that is not minified with terser.~~ (https://github.com/optimizely/javascript-sdk/pull/477 has merged which also adds the unminified ES bundle, so this PR now just makes the unminified bundle the `module` entrypoint.)
Notably, the unminified bundle is created _in addition to_ the minified bundle;
so the …
=> chore: Ship unminified file as ESM entrypoint

.github/workflows/integration_test.yml, .github/workflows/javascript.yml
- FSC needs CLIENT to run js sdk, which was missing in our integration-test yaml. I have made it fixed, once this PR Is merged, we should have proper status of FSC in our checks.
- I have tested in our last checks and works fine. for now i have pointed to master branch which will be used to take configuration for running CI.
=> fix: FSC build CLIENT fix.

packages/datafile-manager/CHANGELOG.md, packages/datafile-manager/package-lock.json, packages/datafile-manager/package.json
- Updated typescript types file path from `lib/index.d.ts` to `lib/index.node.d.ts` in package.json
- Prep for release `0.9.5` for datafile manager
All existing tests pass
=> datafile-manager: typescript types file path updated in package.json

packages/optimizely-sdk/lib/core/custom_attribute_condition_evaluator/index.ts, packages/optimizely-sdk/lib/core/decision_service/index.ts, packages/optimizely-sdk/lib/core/project_config/index.tests.js, packages/optimizely-sdk/lib/core/project_config/index.ts, packages/optimizely-sdk/lib/core/project_config/project_config_schema.ts, packages/optimizely-sdk/lib/optimizely_user_context/index.ts, packages/optimizely-sdk/lib/shared_types.ts, packages/optimizely-sdk/lib/tests/test_data.js
- Parses new datafile odp values (“publicKey” and “host”) from the “integrations” section. These values are used to send requests to the ODP server.
- Parses datafile with and without the “integrations” section or empty section as well.
---
- Added new `integrations` field to the `project_config_schema` composed of array items which are objects with the keys of `key`, `host`, and `publicKey`.
- Added new `Integrations` 
- Added new fields to `ProjectConfig` interface to prepare catching this new incoming `integrations` field:
- `integrations`
- `integrationKeyMap` (Optional)
- `publicKeyForOdp` (Optional)
- `hostForOdp` (Optional)
- `allSegments`
- Exports new `getAudienceSegments` function from project_config. This function is used for recursively evaluating through audience conditions …
=> ODP Datafile Parsing

packages/optimizely-sdk/CHANGELOG.md, packages/optimizely-sdk/lib/index.browser.tests.js, packages/optimizely-sdk/lib/index.lite.tests.js, packages/optimizely-sdk/lib/index.node.tests.js, packages/optimizely-sdk/lib/utils/enums/index.ts, packages/optimizely-sdk/package-lock.json, packages/optimizely-sdk/package.json, packages/optimizely-sdk/tests/index.react_native.spec.ts, packages/optimizely-sdk/tests/odpEventManager.spec.ts
- Incremented Optimizely SDK version from 4.9.2 to 4.9.3
All tests should pass.
- [FSSDK-8887](https://jira.sso.episerver.net/browse/FSSDK-8887)
=> [FSSDK-8887] chore: Prepare release 4.9.3

packages/optimizely-sdk/lib/core/odp/odp_event_manager.ts, packages/optimizely-sdk/tests/odpManager.browser.spec.ts
Allow to disable ODP event batching by setting flushInterval to zero.
- Test flushInterval and batchSize when configured with odpOptions.flushInterval = 0
- [FSSDK-8793](https://jira.sso.episerver.net/browse/FSSDK-8793)
=> feat(ats): [FSSDK-8793] add support for disabling odp event batching

packages/optimizely-sdk/lib/plugins/odp_manager/index.browser.ts, packages/optimizely-sdk/lib/utils/enums/index.ts, packages/optimizely-sdk/tests/odpManager.browser.spec.ts
Support configurable timeouts for ODP segment and event requests.
Use default timeout of 10 secs if not configured.
- Add unit tests for configured and default timeout values
- [FSSDK-8690](https://jira.sso.episerver.net/browse/FSSDK-8690)
=> feat(ats): [FSSDK-8690] fix configurable ODP request timeouts

packages/optimizely-sdk/lib/core/odp/odp_event_api_manager.ts, packages/optimizely-sdk/lib/core/odp/odp_event_manager.ts, packages/optimizely-sdk/lib/core/odp/odp_utils.ts, packages/optimizely-sdk/lib/index.browser.tests.js, packages/optimizely-sdk/lib/optimizely/index.ts, packages/optimizely-sdk/lib/plugins/odp_manager/index.browser.ts, packages/optimizely-sdk/lib/utils/enums/index.ts, packages/optimizely-sdk/tests/odpManager.browser.spec.ts
Changed the behavior of sendOdpEvent in the browser to utilize the ODP Pixel API ([https://jumbe.zaius.com/v2/zaius.gif) ](https://jumbe.zaius.com/v2/zaius.gif) via GET call.
- Key/value pairs from data and identifiers as well as apiKey, type and action are shifted to to the URL query parameters of the GET request.
- Pixel API does not support batching
- added tests to index.browser.tests.js
- existing tests pass
[FSSDK-8993](https://jira.sso.episerver.net/browse/FSSDK-8993)
=> [FSSDK-8993]feat: switch odp event rest endpoint

packages/optimizely-sdk/lib/core/odp/odp_segment_api_manager.ts, packages/optimizely-sdk/lib/core/odp/odp_types.ts, packages/optimizely-sdk/tests/odpSegmentApiManager.spec.ts
Handle INVALID_IDENTIFIER_EXCEPTION error code for fetchQualifiedSegment API call to log a proper error message.
- Fix tests validating fetchQualifiedSegment error codes.
- [FSSDK-9126](https://jira.sso.episerver.net/browse/FSSDK-9126)
- [FSSDK-9133](https://jira.sso.episerver.net/browse/FSSDK-9133)
=> [FSSDK-9126] fix(ats): handle INVALID_IDENTIFIER_EXCEPTION error

.github/workflows/javascript.yml, packages/optimizely-sdk/lib/core/odp/odp_event_manager.ts, packages/optimizely-sdk/lib/index.browser.tests.js, packages/optimizely-sdk/tests/odpEventManager.spec.ts
- Fix "client_initialized" event not firing
- Needs a more detailed set of tests wrapped around for coverage. 
- Existing tests should continue to succeed along with FSC
[FSSDK-9152](https://jira.sso.episerver.net/browse/FSSDK-9152)
=> [FSSDK-9152] Fix "client_initialized" event not firing

packages/optimizely-sdk/CHANGELOG.md, packages/optimizely-sdk/lib/index.browser.tests.js, packages/optimizely-sdk/lib/index.lite.tests.js, packages/optimizely-sdk/lib/index.node.tests.js, packages/optimizely-sdk/lib/utils/enums/index.ts, packages/optimizely-sdk/package-lock.json, packages/optimizely-sdk/package.json, packages/optimizely-sdk/tests/index.react_native.spec.ts
- Incremented Optimizely SDK version from 4.9.3 to 5.0.0-beta.1
Prepare for first v5 Beta Pre-release.
- All existing tests should pass.
- New tests introduced in this version should also pass.
- The known FSC failure will be addressed in a future patch.
- [FSSDK-9096](https://jira.sso.episerver.net/browse/FSSDK-9096)
=> [FSSDK-9096] chore: Prepare release 5.0.0-beta

packages/optimizely-sdk/lib/core/odp/odp_event_manager.ts, packages/optimizely-sdk/lib/plugins/odp/event_manager/index.browser.ts, packages/optimizely-sdk/lib/plugins/odp/event_manager/index.node.ts, packages/optimizely-sdk/tests/odpEventManager.spec.ts
- SendODPEvent API has "identifiers" parameter as optional. For server-sdks (aka Node context), this should be changed to required (at least one key-value pair).
- 2 new unit tests added
- Existing unit tests should continue to pass
- FSC tests should pass
- [FSSDK-8950](https://jira.sso.episerver.net/browse/FSSDK-8950)
=> [FSSDK-8950] change identifiers to be required for sendOdpEvent

packages/optimizely-sdk/lib/optimizely/index.ts, packages/optimizely-sdk/lib/plugins/odp/event_api_manager/index.browser.ts, packages/optimizely-sdk/lib/plugins/odp/event_api_manager/index.node.ts, packages/optimizely-sdk/lib/utils/fns/index.ts
- For browser clients, adds VUID instantiation promise to the client's onReady promise dependencies.
This helps ensure VUID successfully populates before the onReady promise returns for the client, preventing calls to other VUID-dependent functions from failing if VUID hasn't been initialized yet.
- Also adds `isBrowser` utility and includes various formatting cleanup.
- All existing tests should pass.
- [FSSDK-9032](https://jira.sso.episerver.net/browse/FSSDK-9032)
=> [FSSDK-9032] enhancement: Add VUID instantiation to browser client promise dependencies

packages/optimizely-sdk/lib/core/optimizely_config/index.ts
- Previously, OptimizleyConfig instantiation was `O(n^2)` where n = number of feature flags. This has been improved to `O(n)`
- All existing tests should pass. No new test is needed.
- [FSSDK-9417](https://jira.sso.episerver.net/browse/FSSDK-9417)
=> [FSSDK-9417] refactor: improve OptimizelyConfig instantiation performance

packages/optimizely-sdk/lib/optimizely/index.ts
On odp config update:
- All queued odp events should be flushed
- Cache should be reset 
These tests were previously failing because on datafile update, odp config was not being updated. That is fixed in this PR.
- [FSSDK-9361](https://jira.sso.episerver.net/browse/FSSDK-9361)
=> [FSSDK-9361] fix failing fsc tests for odp config update

packages/optimizely-sdk/lib/modules/event_processor/eventQueue.ts, packages/optimizely-sdk/lib/modules/event_processor/managed.ts, packages/optimizely-sdk/lib/modules/event_processor/v1/v1EventProcessor.react_native.ts, packages/optimizely-sdk/lib/modules/event_processor/v1/v1EventProcessor.ts, packages/optimizely-sdk/lib/optimizely/index.ts, packages/optimizely-sdk/lib/plugins/event_processor/forwarding_event_processor.ts
- eventProcessorStartedPromise actually is typed as void in the Managed interface, but has a Promise<void> implementation in the extended EventProcessor interface. This PR fixes that.
- [FSSDK-9416](https://jira.sso.episerver.net/browse/FSSDK-9416)
=> [FSSDK-9416] Refactor dependent promises typing in client onReady

lib/index.browser.tests.js, lib/plugins/odp/event_api_manager/index.browser.ts, lib/plugins/odp_manager/index.node.ts, lib/utils/enums/index.ts
- Previously, pixel api endpoint was fixed. Now pixel api endpoint is generated dynamically from odp apiHost. This is needed cause pixel api endpoints are different for different odp regions.
- All existing tests should pass. 
- FSSDK-9562
=> [FSSDK-9562] set pixel api endpoint dynamically

.vscode/settings.json, lib/core/odp/odp_event_manager.ts, lib/core/odp/user_agent_info.ts, lib/core/odp/user_agent_parser.ts, lib/index.browser.tests.js, lib/index.browser.ts, lib/plugins/odp/user_agent_parser/index.browser.ts, lib/plugins/odp_manager/index.browser.ts, lib/shared_types.ts, package-lock.json, package.json, tests/odpEventManager.spec.ts, tests/odpManager.browser.spec.ts
- added support for user agent parser for odp
- added new tests for validating that ua parser is being used correctly
- tested concrete ua parser manually in browser
- FSSDK-8651
=> [FSSDK-8651] added support for user agent parser for odp

lib/common_exports.ts, lib/index.browser.ts, lib/index.lite.ts, lib/index.node.ts, lib/index.react_native.ts
- Clients like the testapp and react-sdk needs logging types and values, currently they have to import it from deep paths from the lib directory. this PR will allow imports directly for the entrypoint. We will eventually remove lib directory from the published  package bundle.
- FSSDK-9588
=> [FSSDK-9588] export logging types and values

package.json
- remove lib directory from package
- manually created package using `npm pack` and installed and tested in a test project.
- FSSDK-9585
=> [FSSDK-9585] remove lib directory from package

packages/optimizely-sdk/jest.config.js, packages/optimizely-sdk/lib/plugins/event_dispatcher/send_beacon_dispatcher.ts, packages/optimizely-sdk/package-lock.json, packages/optimizely-sdk/package.json, packages/optimizely-sdk/tests/sendBeaconDispatcher.spec.ts
- porting sendBeacon dispatcher to v4. EventProcessor is a separate package in 4.x.x branch. Those changes will be pushed in a separate PR 
-
- FSSDK-9605
=> [FSSDK-9605] add sendBeacon event dispatcher and test

packages/optimizely-sdk/lib/index.browser.ts, packages/optimizely-sdk/lib/shared_types.ts, packages/optimizely-sdk/package-lock.json, packages/optimizely-sdk/package.json
- export and default usage of sendBeaconDispatcher
- FSSDK-9605
=> [FSSDK-9605] export and default usage of sendBeaconDispatcher

lib/core/custom_attribute_condition_evaluator/index.ts, lib/core/decision_service/index.ts, lib/core/event_builder/event_helpers.ts, lib/core/event_builder/index.ts, lib/export_types.ts, lib/optimizely_user_context/index.ts, lib/shared_types.ts
- update type for user attribute values
- FSSDK-8284
=> [FSSDK-8284] Add allowed types to UserAttributes

lib/core/project_config/index.ts, lib/export_types.ts, lib/optimizely/index.ts, lib/shared_types.ts
- getFeatureVariable currently return unknown. Updated the return type to more specific type.
- FSSDK-9897
=> [FSSDK-9897] update return type of getFeatureVariable method

lib/core/odp/odp_config.ts, lib/core/odp/odp_manager.ts, lib/core/project_config/index.tests.js, lib/core/project_config/index.ts, lib/core/project_config/project_config_schema.ts, lib/index.browser.tests.js, lib/optimizely/index.ts, lib/plugins/odp/event_api_manager/index.browser.ts, lib/shared_types.ts, lib/tests/test_data.js, tests/odpEventApiManager.spec.ts, tests/odpEventManager.spec.ts, tests/odpManager.browser.spec.ts, tests/odpManager.spec.ts, tests/odpSegmentManager.spec.ts
- Changed the ODP pixelUrl to be read from the datafile instead of being hard coded in the SDK.
[FSSDK-9607](https://jira.sso.episerver.net/browse/FSSDK-9607)
=> [FSSDK-9607] add pixelUrl to OdpConfig

package.json
- specified package entry points  using the modern [exports field in package.json](https://nodejs.org/api/packages.html#package-entry-points)
- added an export for lite bundle. lite bundle can be now imported using `import optimizely from '@optimizely/optimizely-sdk/lite`
- Tested that the new export entry points are working as expected. Added specific logs to the built files in the dist folder for each specific variant. Then tested that the specific variant is being loaded by installing that locally built sdk in a test project and inspecting the console log. Tested for both browser and node. 
- FSSDK-8983
=> [FSSDK-8983] Specify package entry point using exports field 

lib/index.browser.tests.js, lib/index.browser.ts, lib/index.node.ts, lib/index.react_native.ts, lib/optimizely/index.ts
- When explicit `odpOptions.disabled = true` is passed, avoid ODP instantiation
- Fix Jest test setting in VSCode
- Lint updates
- Existing unit and e2e test suite are expected to pass
- FSSDK-9987
=> [FSSDK-9987] fix: Conditional ODP instantiation

lib/modules/datafile-manager/httpPollingDatafileManager.ts, tests/httpPollingDatafileManager.spec.ts
- log an error when datafile fetch request returns a non success status code
- added test for the logging
- FSSDK-9615
=> [FSSDK-9615] log error when datafile fetch request fails

.github/workflows/javascript.yml, package.json
also add back unit test ci for node14
v5.0.0 was released with engine.node >=14.0.0. So updating this technically constitutes a breaking change.
- FSSDK-9586
=> [FSSDK-9586] restore node engine to >=14

lib/optimizely_user_context/index.tests.js, lib/optimizely_user_context/index.ts
- `fetchQualifiedSegments` returning and empty array `[ ]` is valid
- Added test cases
- FSSDK-9984
=> [FSSDK-9984] fix: Empty fetched qualified segments validity

package-lock.json
- Fix 2 identified deps CVEs
```bash
npm audit
follow-redirects  <=1.15.5
Severity: moderate
follow-redirects' Proxy-Authorization header kept across hosts - https://github.com/advisories/GHSA-cxjh-pqwp-8mfp
fix available via `npm audit fix`
node_modules/follow-redirects
get-func-name  <2.0.1
Severity: high
Chaijs/get-func-name vulnerable to ReDoS - https://github.com/advisories/GHSA-4q6p-r6v2-jvc5
fix available via `npm audit fix`
node_modules/get-func-name
2 vulnerabilities (1 moderate, 1 high)
```
- Hijacking FSSDK-9965
=> [FSSDK-9965] chore: npm audit fix for follow-redirects & get-func-name

lib/core/odp/odp_config.ts, lib/core/odp/odp_event_api_manager.ts, lib/core/odp/odp_event_manager.ts, lib/core/odp/odp_manager.ts, lib/core/odp/odp_segment_manager.ts, lib/core/project_config/index.tests.js, lib/core/project_config/index.ts, lib/core/project_config/project_config_manager.tests.js, lib/core/project_config/project_config_manager.ts, lib/index.browser.tests.js, lib/index.browser.ts, lib/index.node.ts, lib/index.react_native.ts, lib/optimizely/index.tests.js, lib/optimizely/index.ts, lib/optimizely_user_context/index.ts, lib/plugins/odp/event_api_manager/index.browser.ts, lib/plugins/odp/event_api_manager/index.node.ts, lib/plugins/odp_manager/index.browser.ts, lib/plugins/odp_manager/index.node.ts, lib/shared_types.ts, lib/utils/enums/index.ts, lib/utils/promise/resolvablePromise.ts, tests/odpEventApiManager.spec.ts, tests/odpEventManager.spec.ts, tests/odpManager.browser.spec.ts, tests/odpManager.spec.ts, tests/odpSegmentManager.spec.ts, tests/testUtils.ts
Things fixed:
- ODPManager should not be running and scheduling timer if ODP is not integrated to the project (which causes memory leak if one sdk instance is created per request)
- CreateUserContext should work even when called before the datafile is downloaded and should send the `identify` ODP events after datafile download completes
- Other automatic odp events (vuid registration, client initialized) should also be sent after datafile is available and should not be dropped if batching is disabled.
- ODP manager should distinguish between when odp config is still not loaded and when odp is not integrated at all
- made ODP config  immutable
- ODP event manager should not schedule timers to flush events if event batching is disabled (ie batch size == 1)
- other code quality improvements …
=> [FSSDK-10090] Refactor ODP integration

CHANGELOG.md, lib/index.browser.tests.js, lib/index.lite.tests.js, lib/index.node.tests.js, lib/utils/enums/index.ts, package-lock.json, package.json, tests/index.react_native.spec.ts
- Bump semantic version
- Update CHANGELOG.md
- All tests should pass 
- FSSDK-10090
=> [FSSDK-10090] Prepare for v5.3.0 release

lib/plugins/event_dispatcher/index.node.ts
- close req after getting response to release memory immediately (node)
Existing tests should pass
- [FSSDK-10180](https://jira.sso.episerver.net/browse/FSSDK-10180)
=> [FSSDK-10180] close http request after getting response to release memory immediately (node)

lib/core/odp/odp_manager.ts, lib/optimizely/index.ts, lib/shared_types.ts
Client should contain public facing API to provide information about ODP integration
- [FSSDK-10198](https://jira.sso.episerver.net/browse/FSSDK-10198)
=> [FSSDK-10198] making isOdpIntegrated public

package-lock.json
Bumps [ws](https://github.com/websockets/ws), [engine.io](https://github.com/socketio/engine.io) and [socket.io-adapter](https://github.com/socketio/socket.io-adapter). These dependencies needed to be updated together.
Updates `ws` from 7.5.9 to 8.17.1
- [Release notes](https://github.com/websockets/ws/releases)
- [Commits](https://github.com/websockets/ws/compare/7.5.9...8.17.1)
Updates `ws` from 6.2.2 to 8.17.1
- [Release notes](https://github.com/websockets/ws/releases)
- [Commits](https://github.com/websockets/ws/compare/7.5.9...8.17.1)
Updates `ws` from 8.14.2 to 8.17.1
- [Release notes](https://github.com/websockets/ws/releases)
- [Commits](https://github.com/websockets/ws/compare/7.5.9...8.17.1)
Updates `engine.io` from 6.5.2 to 6.5.5
- [Release …
=> [FSSDK-10372] chore(deps): bump ws, engine.io and socket.io-adapter

package-lock.json, package.json
=> [FSSDK-10320] Remove @babel/runtime as a peerDependency

.github/workflows/integration_test.yml, .github/workflows/release.yml
Instead of directly using variables that can contain user input, new intermediate variables were introduced so that script injection attacks could be mitigated. Also **default environment variables** were used wherever possible.
- [FSSDK-10665](https://jira.sso.episerver.net/browse/FSSDK-10665)
=> [FSSDK-10665] fix: Github Actions YAML files vulnerable to script injections corrected

lib/core/decision_service/index.tests.js, lib/core/project_config/index.ts, lib/optimizely/index.ts, lib/shared_types.ts, lib/tests/test_data.js
When "activate" is called with a rollout experiment key (not ab-test), SDK is supposed to return "invalid experiment key". 
An optional `isRollout`  flag property has been added to the experiment object to identify if its a rollout experiment or not.
[FSSDK-10586](https://jira.sso.episerver.net/browse/FSSDK-10586)
=> [FSSDK-10586] rollout experiment key returns wrong decision

lib/core/odp/odp_event_manager.ts, lib/core/odp/odp_manager.ts, lib/optimizely/index.ts, lib/plugins/odp_manager/index.browser.ts, lib/plugins/odp_manager/index.node.ts, tests/odpEventManager.spec.ts, tests/odpManager.spec.ts
- vuid is added automatically to all odp events
- new test added
- FSSDK-10797
=> [FSSDK-10797] send vuid automatically with odp events

lib/index.browser.ts, lib/index.react_native.ts, lib/optimizely/index.ts, lib/plugins/vuid_manager/index.browser.ts, lib/plugins/vuid_manager/index.react_native.ts, lib/plugins/vuid_manager/index.ts, lib/shared_types.ts, tests/vuidManager.spec.ts
- vuid manager interface updates
- updated affected tests and added new tests
- FSSDK-10867
=> [FSSDK-10867] update vuid manager interface

lib/core/decision_service/index.tests.js, lib/core/decision_service/index.ts, lib/optimizely/index.tests.js, lib/optimizely/index.ts, lib/optimizely_user_context/index.tests.js, lib/project_config/project_config.ts, lib/shared_types.ts, lib/tests/test_data.ts, lib/utils/enums/index.ts
Cherry Picking commits  (#949 , #953 ) from 5.x.x to master
- [FSSDK-10934](https://jira.sso.episerver.net/browse/FSSDK-10934)
=> [FSSDK-10934] Cherry picking commits from 5.x.x to master

.gitignore, messageGenerator.ts, message_generator.ts, package-lock.json, package.json
- implement generator to convert log message files
- tested the script manually
- FSSDK-10985
=> [FSSDK-10985] Implement log message file generator

lib/export_types.ts, lib/notification_center/index.tests.js, lib/notification_center/index.ts, lib/notification_center/type.ts, lib/optimizely/index.tests.js, lib/optimizely/index.ts, lib/optimizely_user_context/index.tests.js, lib/shared_types.ts, lib/utils/enums/index.ts, lib/utils/event_emitter/event_emitter.ts
- the notification center api is basically a slightly different version of the event emitter which we are already using in other components. This PR refactors notification center using the event emitter. This will allow us to achieve a slightly smaller bundle size.
- updated tests accordingly
- FSSDK-10989
=> [FSSDK-10989] refactor notification center using event emitter

lib/event_processor/batch_event_processor.spec.ts, lib/event_processor/batch_event_processor.ts, lib/event_processor/event_processor_factory.spec.ts, lib/event_processor/event_processor_factory.ts, lib/exception_messages.ts, lib/odp/event_manager/odp_event_manager.spec.ts, lib/odp/event_manager/odp_event_manager.ts, lib/odp/odp_manager.spec.ts, lib/odp/odp_manager.ts, lib/optimizely/index.spec.ts, lib/optimizely/index.ts, lib/project_config/polling_datafile_manager.spec.ts, lib/project_config/polling_datafile_manager.ts, lib/project_config/project_config_manager.spec.ts, lib/project_config/project_config_manager.ts, lib/service.ts, lib/shared_types.ts, lib/tests/mock/mock_project_config_manager.ts, lib/tests/mock/mock_repeater.ts
Making services disposable will allow the services to be disconnected from the repeater
Test cases have been added
[FSSDK-11003](https://jira.sso.episerver.net/browse/FSSDK-11003)
=> [FSSDK-11003] disposable service implementation

lib/core/decision_service/index.ts, lib/message/error_message.ts, lib/message/log_message.ts, lib/odp/event_manager/odp_event_manager.ts, lib/optimizely/index.tests.js, lib/optimizely/index.ts, lib/optimizely_user_context/index.tests.js, lib/project_config/polling_datafile_manager.ts, lib/project_config/project_config.ts, lib/utils/http_request_handler/request_handler.browser.ts
=> [FSSDK-11090] remove unused log messages

CHANGELOG.md, lib/index.browser.tests.js, lib/index.lite.tests.js, lib/index.node.tests.js, lib/utils/enums/index.ts, package-lock.json, package.json, tests/index.react_native.spec.ts
- #995 
Existing tests should pass
- [FSSDK-11098](https://jira.sso.episerver.net/browse/FSSDK-11098)
=> [FSSDK-11098] prep for release

lib/core/condition_tree_evaluator/index.spec.ts
- Rewrote test case `lib/core/condition_tree_evaluator/index.tests.js` with Typescript
- Converted it from `mocha + sinon + chai` to `vitest`
**PC:** Didn't touch the old test case.
- FSSDK-11095
=> [FSSDK-11095] rewrite condition_tree_evaluator tests in Typescript

lib/export_types.ts, lib/index.browser.ts, lib/optimizely/index.ts, lib/shared_types.ts
=> [FSSDK-11101] cleanup OptimizelyOptions type

lib/message/error_message.ts, lib/optimizely/index.ts
=> [FSSDK-11101] refactor handling of no config availability

lib/core/audience_evaluator/index.spec.ts, lib/core/audience_evaluator/odp_segment_condition_evaluator/index.spec.ts
Re-wrote the following test in typescript:
- lib/core/audience_evaluator/index.tests.js
- lib/core/audience_evaluator/odp_segment_condition_evaluator/index.tests.js
The old tests are written using (mocha + chai + sinon). Used `vitest` features in the new tests.
- FSSDK-11100
=> [FSSDK-11100] JS - rewrite audience_avaluator tests in TypeScript

package.json, rollup.config.js
- manually tested with demo projects for node/browser
- FSSDK-10992
=> [FSSDK-10992] refactor build and export map

lib/project_config/project_config.spec.ts, lib/project_config/project_config.ts, lib/project_config/project_config_schema.ts, lib/shared_types.ts
add cmab experiment properties to project config
- added test for cmab field
- FSSDK-11124
=> [FSSDK-11124] add cmab experiment properties to project config

lib/core/decision_service/cmab/cmab_client.spec.ts, lib/core/decision_service/cmab/cmab_client.ts, lib/message/error_message.ts
- added new tests 
- FSSDK-11125
=> [FSSDK-11125] implement CMAB client

lib/utils/config_validator/index.tests.js, lib/utils/config_validator/index.ts
=> remove obselete validation

lib/core/bucketer/bucket_value_generator.spec.ts, lib/core/bucketer/index.spec.ts, lib/notification_center/index.spec.ts, lib/project_config/project_config.spec.ts, lib/utils/attributes_validator/index.spec.ts, lib/utils/config_validator/index.spec.ts, lib/utils/event_tag_utils/index.spec.ts, lib/utils/event_tags_validator/index.spec.ts, lib/utils/json_schema_validator/index.spec.ts, lib/utils/semantic_version/index.spec.ts, lib/utils/string_value_validator/index.spec.ts, lib/utils/user_profile_service_validator/index.spec.ts
Test conversions from mocha, chai, sinon to vitest
- notification_center
- utils
Tests have been modified
[FSSDK-11238](https://jira.sso.episerver.net/browse/FSSDK-11238)
=> [FSSDK-11238] Test conversions notification_center and utils

lib/odp/odp_manager_factory.browser.spec.ts, lib/odp/odp_manager_factory.browser.ts
=> [FSSDK-11397] replace odp pixel api usage with event api for browser

lib/common_exports.ts, lib/core/decision_service/index.ts, lib/entrypoint.test-d.ts, lib/entrypoint.universal.test-d.ts, lib/notification_center/type.ts, lib/tests/test_data.ts, lib/utils/enums/index.ts, lib/utils/type.ts
=> [FSSDK-11395] add specific type for decision notification

lib/core/decision_service/index.ts, lib/event_processor/batch_event_processor.spec.ts, lib/event_processor/batch_event_processor.ts, lib/event_processor/event_processor.ts, lib/event_processor/forwarding_event_processor.ts, lib/logging/logger.ts, lib/odp/event_manager/odp_event_api_manager.spec.ts, lib/odp/event_manager/odp_event_api_manager.ts, lib/odp/event_manager/odp_event_manager.spec.ts, lib/odp/event_manager/odp_event_manager.ts, lib/odp/odp_manager.spec.ts, lib/odp/odp_manager.ts, lib/odp/segment_manager/odp_segment_api_manager.spec.ts, lib/odp/segment_manager/odp_segment_api_manager.ts, lib/odp/segment_manager/odp_segment_manager.spec.ts, lib/odp/segment_manager/odp_segment_manager.ts, lib/optimizely/index.spec.ts, lib/optimizely/index.tests.js, lib/optimizely/index.ts, lib/project_config/optimizely_config.spec.ts, lib/project_config/polling_datafile_manager.spec.ts, lib/project_config/polling_datafile_manager.ts, lib/project_config/project_config.spec.ts, lib/project_config/project_config_manager.spec.ts, lib/project_config/project_config_manager.ts, lib/tests/mock/mock_logger.ts, lib/tests/mock/mock_project_config_manager.ts
=> [FSSDK-11437] pass logger to all child components

.github/workflows/javascript.yml, package-lock.json
Bumps [vitest](https://github.com/vitest-dev/vitest/tree/HEAD/packages/vitest) and [@vitest/coverage-istanbul](https://github.com/vitest-dev/vitest/tree/HEAD/packages/coverage-istanbul). These dependencies needed to be updated together.
Updates `vitest` from 2.0.5 to 2.1.9
- [Release notes](https://github.com/vitest-dev/vitest/releases)
- [Commits](https://github.com/vitest-dev/vitest/commits/v2.1.9/packages/vitest)
Updates `@vitest/coverage-istanbul` from 2.0.5 to 2.1.9
- [Release notes](https://github.com/vitest-dev/vitest/releases)
- [Commits](https://github.com/vitest-dev/vitest/commits/v2.1.9/packages/coverage-istanbul)
---
updated-dependencies:
- dependency-name: vitest dependency-version: 2.1.9 dependency-type: direct:development
- dependency-name: "@vitest/coverage-istanbul" …
=> [FSSDK-11470] Bump vitest and @vitest/coverage-istanbul

lib/core/event_builder/build_event_v1.ts, lib/modules/event_processor/events.ts, lib/modules/event_processor/v1/buildEventV1.ts, lib/shared_types.ts, lib/utils/event_tag_utils/index.ts
`EvenTags` type fix.
FSSDK-11197
=> [FSSDK-11197] EventTags type fix for v5

lib/core/decision_service/index.spec.ts, lib/event_processor/event_builder/log_event.ts, lib/event_processor/event_builder/user_event.ts, lib/optimizely_user_context/index.tests.js, lib/optimizely_user_context/index.ts, lib/shared_types.ts, lib/utils/enums/index.ts
- Current type does not work when there are control attributes. This PR fixes that
- FSSDK-11494
=> [FSSDK-11494] fix UserAttributes type

lib/project_config/project_config_manager.spec.ts, lib/project_config/project_config_manager.ts
- fire the project config updates synchronously. this will allow the optimizely class to propagate the initial project config synchronously to all sub components. This can be useful when the client is initialized with a datafile. One downside is, the update event handler needs to be registered before calling start() on the config manager, but since we only use the config manager internally, we can maintain that.
- FSSDK-11497
=> [FSSDK-11497] fire config update events synchronously

lib/entrypoint.universal.test-d.ts, lib/export_types.ts, lib/index.universal.ts, lib/odp/odp_manager_factory.browser.spec.ts, lib/odp/odp_manager_factory.node.spec.ts, lib/odp/odp_manager_factory.node.ts, lib/odp/odp_manager_factory.react_native.spec.ts, lib/odp/odp_manager_factory.spec.ts, lib/odp/odp_manager_factory.ts, lib/odp/odp_manager_factory.universal.ts, lib/vuid/vuid_manager_factory.browser.ts
=> [FSSDK-11512] remove eventManager and segmentManager from odp public api

lib/common_exports.ts, lib/entrypoint.test-d.ts, lib/entrypoint.universal.test-d.ts, lib/event_processor/batch_event_processor.spec.ts, lib/logging/logger_factory.spec.ts, lib/logging/logger_factory.ts, lib/project_config/polling_datafile_manager.spec.ts
=> [FSSDK-11504] rename log level presets

lib/event_processor/event_dispatcher/default_dispatcher.spec.ts, lib/event_processor/event_dispatcher/default_dispatcher.ts, lib/utils/http_request_handler/request_handler.node.ts
`content-length` header has been moved to Node from common (Browser & Node).
Existing test has been modified accordingly
[FSSDK-11483](https://jira.sso.episerver.net/browse/FSSDK-11483)
=> [FSSDK-11483] content-length header removal from browser

lib/optimizely_user_context/index.ts
Following async version of decide methods are added to the user context 
- decideAsync
- decideForKeysAsync
- decideAllAsync
[FSSDK-11502](https://jira.sso.episerver.net/browse/FSSDK-11502)
=> [FSSDK-11502] async decide methods addition

lib/core/decision_service/cmab/cmab_service.ts, lib/event_processor/batch_event_processor.ts, lib/event_processor/event_processor_factory.browser.spec.ts, lib/event_processor/event_processor_factory.browser.ts, lib/event_processor/event_processor_factory.node.spec.ts, lib/event_processor/event_processor_factory.react_native.spec.ts, lib/event_processor/event_processor_factory.react_native.ts, lib/event_processor/event_processor_factory.ts, lib/odp/segment_manager/odp_segment_manager.ts, lib/project_config/config_manager_factory.ts, lib/project_config/datafile_manager.ts, lib/project_config/polling_datafile_manager.ts, lib/tests/mock/mock_cache.ts, lib/utils/cache/async_storage_cache.react_native.ts, lib/utils/cache/cache.ts, lib/utils/cache/in_memory_lru_cache.spec.ts, lib/utils/cache/in_memory_lru_cache.ts, lib/utils/cache/local_storage_cache.browser.ts, lib/utils/cache/store.spec.ts, lib/utils/cache/store.ts, lib/vuid/vuid_manager.ts, lib/vuid/vuid_manager_factory.ts
- update the cache interface to be consistent with other sdks.
- FSSDK-11505
=> [FSSDK-11505] update cache interface

lib/event_processor/batch_event_processor.spec.ts, lib/event_processor/batch_event_processor.ts, lib/message/log_message.ts
- saving failed events in the event store indefinitely might cause an app to consume too much storage space. This PR limits the number of events stored in the eventStore.
- added tests
- FSSDK-11513
=> [FSSDK-11513] limit number of events in the eventStore

lib/entrypoint.test-d.ts, lib/index.browser.ts, lib/index.node.ts, lib/index.react_native.ts, lib/vuid/vuid_manager_factory.browser.spec.ts, lib/vuid/vuid_manager_factory.node.spec.ts, lib/vuid/vuid_manager_factory.node.ts, lib/vuid/vuid_manager_factory.ts
- previously we were throwing from unsupported factories. This PR changes them to return undefined instead. It will make writing isomorphic apps easier.
- FSSDK-11510
=> [FSSDK-11510] refactor unsupported factories to not throw

CHANGELOG.md, lib/export_types.ts
- Added missing changelog
- Store type export
- [FSSDK-11515](https://jira.sso.episerver.net/browse/FSSDK-11515)
=> [FSSDK-11515] changelog update

lib/core/bucketer/index.spec.ts, lib/core/bucketer/index.tests.js, lib/core/bucketer/index.ts, lib/core/decision_service/index.tests.js, lib/core/decision_service/index.ts, lib/shared_types.ts
for cmab, we are using a dummy entityId which is not a real variation id. We need to skip entity validation for cmab experiments.
- FSSDK-11132
=> [FSSDK-11132] make entity validation configurable in bucketer

lib/event_processor/batch_event_processor.ts, lib/event_processor/event_builder/log_event.spec.ts, lib/event_processor/event_builder/log_event.ts, lib/event_processor/event_builder/user_event.ts
- remove redundant functions
- small update in batch event processor eventStoreInCount maintenance logic 
- FSSDK-11638
=> [FSSDK-11638] cleanups in event processing

lib/event_processor/event_builder/log_event.spec.ts, lib/event_processor/event_builder/log_event.ts, lib/event_processor/event_builder/user_event.spec.ts, lib/event_processor/event_builder/user_event.tests.js, lib/event_processor/event_builder/user_event.ts, lib/project_config/project_config.spec.ts, lib/project_config/project_config.ts
logx event will now be dispatched to different urls based on region field in the datafile
- added and upldated relevant tests
- FSSDK-11207
=> [FSSDK-11207] add multi region support for logx events

lib/core/bucketer/index.ts, lib/core/decision_service/index.spec.ts, lib/core/decision_service/index.ts, lib/notification_center/type.ts, lib/optimizely/index.ts, lib/project_config/project_config.ts, lib/shared_types.ts, lib/utils/enums/index.ts
Added holdout support in decision service and minor project config adjustments
Tests have been added to support the new implementation
- [FSSDK-11528](https://jira.sso.episerver.net/browse/FSSDK-11528)
=> [FSSDK-11528] Holdout support in decision service

lib/project_config/project_config.ts, lib/utils/fns/index.spec.ts, lib/utils/fns/index.ts
Currently, variationIdMap is being populated as follows:
```
projectConfig.variationIdMap = {
...projectConfig.variationIdMap,
...keyBy(experiment.variations, 'id')
};
```
This creates a new objects for each experiment unnecessarily. This causes large slowdown in project config parsing for datafiles containing a large number of experiments containing a large number of variations. 
This PR makes this more efficient.
- FSSDK-11787
- #1079
=> [FSSDK-11787] fix config parsing performance

lib/feature_toggle.ts, lib/notification_center/type.ts, lib/optimizely/index.spec.ts, lib/optimizely/index.tests.js, lib/optimizely/index.ts, lib/shared_types.ts
The current type of activate listener payload is not backwards compatible with the type in v6.0.0. This PR makes it compatible.
- FSSDK-11823
=> [FSSDK-11823] make Activate listener payload type backwards compatible

lib/core/decision_service/cmab/cmab_service.spec.ts, lib/core/decision_service/cmab/cmab_service.ts, lib/utils/executor/serial_runner.spec.ts, lib/utils/executor/serial_runner.ts
The cmab service caches the results of a cmab prediction retrieved from the server and returns it for subsequent calls. This ensures a consistent value is returned for getDecision() within the cache ttl. However, when there is no cached value, if there are concurrent calls to gertDecision() for same userId and ruleId combination, all of these will cause a call to the server and may potentially return different values.
The solution is to run concurrent calls for same userId and ruleId combinations one after another. To achieve this, we put each (userId, ruleId) combination in one of the predefined bucktes by hashing the (userId, ruleId) combination and serialize all calls for that particular hash % (num_buckets).
- added tests
- FSSDK-11898
=> [FSSDK-11898] serialize concurrent cmab service calls

lib/client_factory.ts, lib/event_processor/batch_event_processor.spec.ts, lib/event_processor/batch_event_processor.ts, lib/event_processor/event_builder/log_event.ts, lib/event_processor/event_processor.ts, lib/event_processor/forwarding_event_processor.ts, lib/index.browser.ts, lib/odp/event_manager/odp_event_manager.spec.ts, lib/odp/event_manager/odp_event_manager.ts, lib/odp/odp_manager.spec.ts, lib/odp/odp_manager.ts, lib/optimizely/index.spec.ts, lib/optimizely/index.ts, package-lock.json, package.json
Currently, in browser, when the page is unloaded, the sdk instance is being closed in order to flush pending events. But when the page is loaded from [bfcache](https://developer.mozilla.org/en-US/docs/Glossary/bfcache), the sdk instance stays closed as bfcache restores the Javascript heap as well, which causes further events to be not processed. 
This PR updates the code to flush events on page unload without closing the sdk instance.
- added tests
- FSSDK-11879
- #1084
=>     [FSSDK-11879] flush events without closing client on page unload
